2023-08-07 21:23:32,835:WARNING:
'cuml' is a soft dependency and not included in the pycaret installation. Please run: `pip install cuml` to install.
2023-08-07 21:23:32,835:WARNING:
'cuml' is a soft dependency and not included in the pycaret installation. Please run: `pip install cuml` to install.
2023-08-07 21:23:32,836:WARNING:
'cuml' is a soft dependency and not included in the pycaret installation. Please run: `pip install cuml` to install.
2023-08-07 21:23:32,836:WARNING:
'cuml' is a soft dependency and not included in the pycaret installation. Please run: `pip install cuml` to install.
2023-08-07 21:23:34,111:INFO:PyCaret ClassificationExperiment
2023-08-07 21:23:34,111:INFO:Logging name: clf-default-name
2023-08-07 21:23:34,112:INFO:ML Usecase: MLUsecase.CLASSIFICATION
2023-08-07 21:23:34,112:INFO:version 3.0.4
2023-08-07 21:23:34,112:INFO:Initializing setup()
2023-08-07 21:23:34,112:INFO:self.USI: 28e9
2023-08-07 21:23:34,112:INFO:self._variable_keys: {'gpu_n_jobs_param', 'exp_name_log', 'y_test', 'USI', 'log_plots_param', 'memory', 'exp_id', 'fold_groups_param', 'y_train', '_ml_usecase', 'is_multiclass', 'data', 'seed', 'target_param', '_available_plots', 'idx', 'fix_imbalance', 'n_jobs_param', 'gpu_param', 'X_test', 'fold_generator', 'X', 'pipeline', 'html_param', 'X_train', 'fold_shuffle_param', 'logging_param', 'y'}
2023-08-07 21:23:34,112:INFO:Checking environment
2023-08-07 21:23:34,113:INFO:python_version: 3.10.9
2023-08-07 21:23:34,113:INFO:python_build: ('main', 'Mar  1 2023 18:18:15')
2023-08-07 21:23:34,113:INFO:machine: AMD64
2023-08-07 21:23:34,113:INFO:platform: Windows-10-10.0.19045-SP0
2023-08-07 21:23:34,113:INFO:Memory: svmem(total=17031249920, available=7321362432, percent=57.0, used=9709887488, free=7321362432)
2023-08-07 21:23:34,113:INFO:Physical Core: 4
2023-08-07 21:23:34,113:INFO:Logical Core: 8
2023-08-07 21:23:34,113:INFO:Checking libraries
2023-08-07 21:23:34,113:INFO:System:
2023-08-07 21:23:34,113:INFO:    python: 3.10.9 | packaged by Anaconda, Inc. | (main, Mar  1 2023, 18:18:15) [MSC v.1916 64 bit (AMD64)]
2023-08-07 21:23:34,113:INFO:executable: C:\Users\Sajjad Sindhi\AppData\Local\anaconda3\python.exe
2023-08-07 21:23:34,113:INFO:   machine: Windows-10-10.0.19045-SP0
2023-08-07 21:23:34,113:INFO:PyCaret required dependencies:
2023-08-07 21:23:35,492:INFO:                 pip: 22.3.1
2023-08-07 21:23:35,493:INFO:          setuptools: 65.6.3
2023-08-07 21:23:35,493:INFO:             pycaret: 3.0.4
2023-08-07 21:23:35,493:INFO:             IPython: 8.10.0
2023-08-07 21:23:35,493:INFO:          ipywidgets: 7.6.5
2023-08-07 21:23:35,494:INFO:                tqdm: 4.64.1
2023-08-07 21:23:35,494:INFO:               numpy: 1.23.5
2023-08-07 21:23:35,494:INFO:              pandas: 1.5.3
2023-08-07 21:23:35,494:INFO:              jinja2: 3.1.2
2023-08-07 21:23:35,494:INFO:               scipy: 1.10.0
2023-08-07 21:23:35,495:INFO:              joblib: 1.3.1
2023-08-07 21:23:35,495:INFO:             sklearn: 1.2.1
2023-08-07 21:23:35,495:INFO:                pyod: 1.1.0
2023-08-07 21:23:35,495:INFO:            imblearn: 0.10.1
2023-08-07 21:23:35,495:INFO:   category_encoders: 2.6.1
2023-08-07 21:23:35,495:INFO:            lightgbm: 4.0.0
2023-08-07 21:23:35,496:INFO:               numba: 0.56.4
2023-08-07 21:23:35,496:INFO:            requests: 2.28.1
2023-08-07 21:23:35,496:INFO:          matplotlib: 3.7.0
2023-08-07 21:23:35,496:INFO:          scikitplot: 0.3.7
2023-08-07 21:23:35,496:INFO:         yellowbrick: 1.5
2023-08-07 21:23:35,497:INFO:              plotly: 5.9.0
2023-08-07 21:23:35,497:INFO:    plotly-resampler: Not installed
2023-08-07 21:23:35,497:INFO:             kaleido: 0.2.1
2023-08-07 21:23:35,497:INFO:           schemdraw: 0.15
2023-08-07 21:23:35,497:INFO:         statsmodels: 0.13.5
2023-08-07 21:23:35,497:INFO:              sktime: 0.21.0
2023-08-07 21:23:35,498:INFO:               tbats: 1.1.3
2023-08-07 21:23:35,498:INFO:            pmdarima: 2.0.3
2023-08-07 21:23:35,498:INFO:              psutil: 5.9.0
2023-08-07 21:23:35,499:INFO:          markupsafe: 2.1.1
2023-08-07 21:23:35,499:INFO:             pickle5: Not installed
2023-08-07 21:23:35,499:INFO:         cloudpickle: 2.0.0
2023-08-07 21:23:35,499:INFO:         deprecation: 2.1.0
2023-08-07 21:23:35,499:INFO:              xxhash: 3.3.0
2023-08-07 21:23:35,500:INFO:           wurlitzer: Not installed
2023-08-07 21:23:35,500:INFO:PyCaret optional dependencies:
2023-08-07 21:23:35,578:INFO:                shap: Not installed
2023-08-07 21:23:35,578:INFO:           interpret: Not installed
2023-08-07 21:23:35,579:INFO:                umap: Not installed
2023-08-07 21:23:35,579:INFO:    pandas_profiling: Not installed
2023-08-07 21:23:35,579:INFO:  explainerdashboard: Not installed
2023-08-07 21:23:35,580:INFO:             autoviz: Not installed
2023-08-07 21:23:35,580:INFO:           fairlearn: Not installed
2023-08-07 21:23:35,580:INFO:          deepchecks: Not installed
2023-08-07 21:23:35,580:INFO:             xgboost: Not installed
2023-08-07 21:23:35,581:INFO:            catboost: Not installed
2023-08-07 21:23:35,581:INFO:              kmodes: Not installed
2023-08-07 21:23:35,581:INFO:             mlxtend: Not installed
2023-08-07 21:23:35,582:INFO:       statsforecast: Not installed
2023-08-07 21:23:35,582:INFO:        tune_sklearn: Not installed
2023-08-07 21:23:35,583:INFO:                 ray: Not installed
2023-08-07 21:23:35,583:INFO:            hyperopt: Not installed
2023-08-07 21:23:35,583:INFO:              optuna: Not installed
2023-08-07 21:23:35,584:INFO:               skopt: Not installed
2023-08-07 21:23:35,584:INFO:              mlflow: Not installed
2023-08-07 21:23:35,584:INFO:              gradio: Not installed
2023-08-07 21:23:35,584:INFO:             fastapi: Not installed
2023-08-07 21:23:35,584:INFO:             uvicorn: Not installed
2023-08-07 21:23:35,584:INFO:              m2cgen: Not installed
2023-08-07 21:23:35,585:INFO:           evidently: Not installed
2023-08-07 21:23:35,585:INFO:               fugue: Not installed
2023-08-07 21:23:35,585:INFO:           streamlit: 1.24.0
2023-08-07 21:23:35,585:INFO:             prophet: Not installed
2023-08-07 21:23:35,585:INFO:None
2023-08-07 21:23:35,586:INFO:Set up data.
2023-08-07 21:23:35,594:INFO:Set up train/test split.
2023-08-07 21:23:35,607:INFO:Set up index.
2023-08-07 21:23:35,607:INFO:Set up folding strategy.
2023-08-07 21:23:35,608:INFO:Assigning column types.
2023-08-07 21:23:35,618:INFO:Engine successfully changes for model 'lr' to 'sklearn'.
2023-08-07 21:23:35,744:INFO:Engine for model 'knn' has not been set explicitly, hence returning None.
2023-08-07 21:23:35,752:INFO:Engine for model 'rbfsvm' has not been set explicitly, hence returning None.
2023-08-07 21:23:35,852:WARNING:
'xgboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install xgboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2023-08-07 21:23:35,852:WARNING:
'catboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install catboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2023-08-07 21:23:35,975:INFO:Engine for model 'knn' has not been set explicitly, hence returning None.
2023-08-07 21:23:35,978:INFO:Engine for model 'rbfsvm' has not been set explicitly, hence returning None.
2023-08-07 21:23:36,064:WARNING:
'xgboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install xgboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2023-08-07 21:23:36,065:WARNING:
'catboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install catboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2023-08-07 21:23:36,066:INFO:Engine successfully changes for model 'knn' to 'sklearn'.
2023-08-07 21:23:36,189:INFO:Engine for model 'rbfsvm' has not been set explicitly, hence returning None.
2023-08-07 21:23:36,269:WARNING:
'xgboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install xgboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2023-08-07 21:23:36,270:WARNING:
'catboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install catboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2023-08-07 21:23:36,395:INFO:Engine for model 'rbfsvm' has not been set explicitly, hence returning None.
2023-08-07 21:23:36,463:WARNING:
'xgboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install xgboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2023-08-07 21:23:36,463:WARNING:
'catboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install catboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2023-08-07 21:23:36,464:INFO:Engine successfully changes for model 'rbfsvm' to 'sklearn'.
2023-08-07 21:23:36,697:WARNING:
'xgboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install xgboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2023-08-07 21:23:36,699:WARNING:
'catboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install catboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2023-08-07 21:23:36,904:WARNING:
'xgboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install xgboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2023-08-07 21:23:36,905:WARNING:
'catboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install catboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2023-08-07 21:23:36,910:INFO:Preparing preprocessing pipeline...
2023-08-07 21:23:36,912:INFO:Set up simple imputation.
2023-08-07 21:23:36,914:INFO:Set up column name cleaning.
2023-08-07 21:23:36,978:INFO:Finished creating preprocessing pipeline.
2023-08-07 21:23:36,996:INFO:Pipeline: Pipeline(memory=FastMemory(location=C:\Users\SAJJAD~1\AppData\Local\Temp\joblib),
         steps=[('numerical_imputer',
                 TransformerWrapper(exclude=None,
                                    include=['Number of times pregnant',
                                             'Plasma glucose concentration a 2 '
                                             'hours in an oral glucose '
                                             'tolerance test',
                                             'Diastolic blood pressure (mm Hg)',
                                             'Triceps skin fold thickness (mm)',
                                             '2-Hour serum insulin (mu U/ml)',
                                             'Body mass index (we...
                 TransformerWrapper(exclude=None, include=[],
                                    transformer=SimpleImputer(add_indicator=False,
                                                              copy=True,
                                                              fill_value=None,
                                                              keep_empty_features=False,
                                                              missing_values=nan,
                                                              strategy='most_frequent',
                                                              verbose='deprecated'))),
                ('clean_column_names',
                 TransformerWrapper(exclude=None, include=None,
                                    transformer=CleanColumnNames(match='[\\]\\[\\,\\{\\}\\"\\:]+')))],
         verbose=False)
2023-08-07 21:23:36,996:INFO:Creating final display dataframe.
2023-08-07 21:23:37,237:INFO:Setup _display_container:                     Description             Value
0                    Session id               123
1                        Target    Class variable
2                   Target type            Binary
3           Original data shape          (768, 9)
4        Transformed data shape          (768, 9)
5   Transformed train set shape          (537, 9)
6    Transformed test set shape          (231, 9)
7              Numeric features                 8
8                    Preprocess              True
9               Imputation type            simple
10           Numeric imputation              mean
11       Categorical imputation              mode
12               Fold Generator   StratifiedKFold
13                  Fold Number                10
14                     CPU Jobs                -1
15                      Use GPU             False
16               Log Experiment             False
17              Experiment Name  clf-default-name
18                          USI              28e9
2023-08-07 21:23:37,452:WARNING:
'xgboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install xgboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2023-08-07 21:23:37,452:WARNING:
'catboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install catboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2023-08-07 21:23:37,645:WARNING:
'xgboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install xgboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2023-08-07 21:23:37,646:WARNING:
'catboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install catboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2023-08-07 21:23:37,647:INFO:setup() successfully completed in 3.65s...............
2023-08-07 21:23:43,060:INFO:PyCaret ClassificationExperiment
2023-08-07 21:23:43,060:INFO:Logging name: clf-default-name
2023-08-07 21:23:43,060:INFO:ML Usecase: MLUsecase.CLASSIFICATION
2023-08-07 21:23:43,060:INFO:version 3.0.4
2023-08-07 21:23:43,061:INFO:Initializing setup()
2023-08-07 21:23:43,061:INFO:self.USI: d013
2023-08-07 21:23:43,061:INFO:self._variable_keys: {'gpu_n_jobs_param', 'exp_name_log', 'y_test', 'USI', 'log_plots_param', 'memory', 'exp_id', 'fold_groups_param', 'y_train', '_ml_usecase', 'is_multiclass', 'data', 'seed', 'target_param', '_available_plots', 'idx', 'fix_imbalance', 'n_jobs_param', 'gpu_param', 'X_test', 'fold_generator', 'X', 'pipeline', 'html_param', 'X_train', 'fold_shuffle_param', 'logging_param', 'y'}
2023-08-07 21:23:43,061:INFO:Checking environment
2023-08-07 21:23:43,061:INFO:python_version: 3.10.9
2023-08-07 21:23:43,062:INFO:python_build: ('main', 'Mar  1 2023 18:18:15')
2023-08-07 21:23:43,062:INFO:machine: AMD64
2023-08-07 21:23:43,062:INFO:platform: Windows-10-10.0.19045-SP0
2023-08-07 21:23:43,062:INFO:Memory: svmem(total=17031249920, available=7288217600, percent=57.2, used=9743032320, free=7288217600)
2023-08-07 21:23:43,062:INFO:Physical Core: 4
2023-08-07 21:23:43,063:INFO:Logical Core: 8
2023-08-07 21:23:43,063:INFO:Checking libraries
2023-08-07 21:23:43,063:INFO:System:
2023-08-07 21:23:43,063:INFO:    python: 3.10.9 | packaged by Anaconda, Inc. | (main, Mar  1 2023, 18:18:15) [MSC v.1916 64 bit (AMD64)]
2023-08-07 21:23:43,064:INFO:executable: C:\Users\Sajjad Sindhi\AppData\Local\anaconda3\python.exe
2023-08-07 21:23:43,064:INFO:   machine: Windows-10-10.0.19045-SP0
2023-08-07 21:23:43,064:INFO:PyCaret required dependencies:
2023-08-07 21:23:43,064:INFO:                 pip: 22.3.1
2023-08-07 21:23:43,065:INFO:          setuptools: 65.6.3
2023-08-07 21:23:43,065:INFO:             pycaret: 3.0.4
2023-08-07 21:23:43,065:INFO:             IPython: 8.10.0
2023-08-07 21:23:43,065:INFO:          ipywidgets: 7.6.5
2023-08-07 21:23:43,066:INFO:                tqdm: 4.64.1
2023-08-07 21:23:43,066:INFO:               numpy: 1.23.5
2023-08-07 21:23:43,066:INFO:              pandas: 1.5.3
2023-08-07 21:23:43,066:INFO:              jinja2: 3.1.2
2023-08-07 21:23:43,066:INFO:               scipy: 1.10.0
2023-08-07 21:23:43,066:INFO:              joblib: 1.3.1
2023-08-07 21:23:43,067:INFO:             sklearn: 1.2.1
2023-08-07 21:23:43,067:INFO:                pyod: 1.1.0
2023-08-07 21:23:43,067:INFO:            imblearn: 0.10.1
2023-08-07 21:23:43,067:INFO:   category_encoders: 2.6.1
2023-08-07 21:23:43,067:INFO:            lightgbm: 4.0.0
2023-08-07 21:23:43,068:INFO:               numba: 0.56.4
2023-08-07 21:23:43,068:INFO:            requests: 2.28.1
2023-08-07 21:23:43,068:INFO:          matplotlib: 3.7.0
2023-08-07 21:23:43,068:INFO:          scikitplot: 0.3.7
2023-08-07 21:23:43,068:INFO:         yellowbrick: 1.5
2023-08-07 21:23:43,068:INFO:              plotly: 5.9.0
2023-08-07 21:23:43,069:INFO:    plotly-resampler: Not installed
2023-08-07 21:23:43,069:INFO:             kaleido: 0.2.1
2023-08-07 21:23:43,069:INFO:           schemdraw: 0.15
2023-08-07 21:23:43,069:INFO:         statsmodels: 0.13.5
2023-08-07 21:23:43,069:INFO:              sktime: 0.21.0
2023-08-07 21:23:43,070:INFO:               tbats: 1.1.3
2023-08-07 21:23:43,070:INFO:            pmdarima: 2.0.3
2023-08-07 21:23:43,070:INFO:              psutil: 5.9.0
2023-08-07 21:23:43,070:INFO:          markupsafe: 2.1.1
2023-08-07 21:23:43,070:INFO:             pickle5: Not installed
2023-08-07 21:23:43,071:INFO:         cloudpickle: 2.0.0
2023-08-07 21:23:43,071:INFO:         deprecation: 2.1.0
2023-08-07 21:23:43,071:INFO:              xxhash: 3.3.0
2023-08-07 21:23:43,071:INFO:           wurlitzer: Not installed
2023-08-07 21:23:43,071:INFO:PyCaret optional dependencies:
2023-08-07 21:23:43,072:INFO:                shap: Not installed
2023-08-07 21:23:43,072:INFO:           interpret: Not installed
2023-08-07 21:23:43,072:INFO:                umap: Not installed
2023-08-07 21:23:43,072:INFO:    pandas_profiling: Not installed
2023-08-07 21:23:43,072:INFO:  explainerdashboard: Not installed
2023-08-07 21:23:43,073:INFO:             autoviz: Not installed
2023-08-07 21:23:43,073:INFO:           fairlearn: Not installed
2023-08-07 21:23:43,073:INFO:          deepchecks: Not installed
2023-08-07 21:23:43,073:INFO:             xgboost: Not installed
2023-08-07 21:23:43,073:INFO:            catboost: Not installed
2023-08-07 21:23:43,074:INFO:              kmodes: Not installed
2023-08-07 21:23:43,074:INFO:             mlxtend: Not installed
2023-08-07 21:23:43,074:INFO:       statsforecast: Not installed
2023-08-07 21:23:43,074:INFO:        tune_sklearn: Not installed
2023-08-07 21:23:43,074:INFO:                 ray: Not installed
2023-08-07 21:23:43,074:INFO:            hyperopt: Not installed
2023-08-07 21:23:43,075:INFO:              optuna: Not installed
2023-08-07 21:23:43,075:INFO:               skopt: Not installed
2023-08-07 21:23:43,075:INFO:              mlflow: Not installed
2023-08-07 21:23:43,075:INFO:              gradio: Not installed
2023-08-07 21:23:43,075:INFO:             fastapi: Not installed
2023-08-07 21:23:43,076:INFO:             uvicorn: Not installed
2023-08-07 21:23:43,076:INFO:              m2cgen: Not installed
2023-08-07 21:23:43,076:INFO:           evidently: Not installed
2023-08-07 21:23:43,076:INFO:               fugue: Not installed
2023-08-07 21:23:43,076:INFO:           streamlit: 1.24.0
2023-08-07 21:23:43,076:INFO:             prophet: Not installed
2023-08-07 21:23:43,077:INFO:None
2023-08-07 21:23:43,077:INFO:Set up data.
2023-08-07 21:23:43,090:INFO:Set up train/test split.
2023-08-07 21:23:43,102:INFO:Set up index.
2023-08-07 21:23:43,102:INFO:Set up folding strategy.
2023-08-07 21:23:43,103:INFO:Assigning column types.
2023-08-07 21:23:43,112:INFO:Engine successfully changes for model 'lr' to 'sklearn'.
2023-08-07 21:23:43,241:INFO:Engine for model 'knn' has not been set explicitly, hence returning None.
2023-08-07 21:23:43,243:INFO:Engine for model 'rbfsvm' has not been set explicitly, hence returning None.
2023-08-07 21:23:43,321:WARNING:
'xgboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install xgboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2023-08-07 21:23:43,323:WARNING:
'catboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install catboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2023-08-07 21:23:43,435:INFO:Engine for model 'knn' has not been set explicitly, hence returning None.
2023-08-07 21:23:43,436:INFO:Engine for model 'rbfsvm' has not been set explicitly, hence returning None.
2023-08-07 21:23:43,503:WARNING:
'xgboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install xgboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2023-08-07 21:23:43,504:WARNING:
'catboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install catboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2023-08-07 21:23:43,505:INFO:Engine successfully changes for model 'knn' to 'sklearn'.
2023-08-07 21:23:43,605:INFO:Engine for model 'rbfsvm' has not been set explicitly, hence returning None.
2023-08-07 21:23:43,680:WARNING:
'xgboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install xgboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2023-08-07 21:23:43,681:WARNING:
'catboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install catboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2023-08-07 21:23:43,803:INFO:Engine for model 'rbfsvm' has not been set explicitly, hence returning None.
2023-08-07 21:23:43,844:WARNING:
'xgboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install xgboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2023-08-07 21:23:43,844:WARNING:
'catboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install catboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2023-08-07 21:23:43,845:INFO:Engine successfully changes for model 'rbfsvm' to 'sklearn'.
2023-08-07 21:23:43,954:WARNING:
'xgboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install xgboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2023-08-07 21:23:43,955:WARNING:
'catboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install catboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2023-08-07 21:23:44,199:WARNING:
'xgboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install xgboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2023-08-07 21:23:44,200:WARNING:
'catboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install catboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2023-08-07 21:23:44,203:INFO:Preparing preprocessing pipeline...
2023-08-07 21:23:44,205:INFO:Set up simple imputation.
2023-08-07 21:23:44,207:INFO:Set up column name cleaning.
2023-08-07 21:23:44,271:INFO:Finished creating preprocessing pipeline.
2023-08-07 21:23:44,285:INFO:Pipeline: Pipeline(memory=FastMemory(location=C:\Users\SAJJAD~1\AppData\Local\Temp\joblib),
         steps=[('numerical_imputer',
                 TransformerWrapper(exclude=None,
                                    include=['Number of times pregnant',
                                             'Plasma glucose concentration a 2 '
                                             'hours in an oral glucose '
                                             'tolerance test',
                                             'Diastolic blood pressure (mm Hg)',
                                             'Triceps skin fold thickness (mm)',
                                             '2-Hour serum insulin (mu U/ml)',
                                             'Body mass index (we...
                 TransformerWrapper(exclude=None, include=[],
                                    transformer=SimpleImputer(add_indicator=False,
                                                              copy=True,
                                                              fill_value=None,
                                                              keep_empty_features=False,
                                                              missing_values=nan,
                                                              strategy='most_frequent',
                                                              verbose='deprecated'))),
                ('clean_column_names',
                 TransformerWrapper(exclude=None, include=None,
                                    transformer=CleanColumnNames(match='[\\]\\[\\,\\{\\}\\"\\:]+')))],
         verbose=False)
2023-08-07 21:23:44,285:INFO:Creating final display dataframe.
2023-08-07 21:23:44,507:INFO:Setup _display_container:                     Description             Value
0                    Session id               123
1                        Target    Class variable
2                   Target type            Binary
3           Original data shape          (768, 9)
4        Transformed data shape          (768, 9)
5   Transformed train set shape          (537, 9)
6    Transformed test set shape          (231, 9)
7              Numeric features                 8
8                    Preprocess              True
9               Imputation type            simple
10           Numeric imputation              mean
11       Categorical imputation              mode
12               Fold Generator   StratifiedKFold
13                  Fold Number                10
14                     CPU Jobs                -1
15                      Use GPU             False
16               Log Experiment             False
17              Experiment Name  clf-default-name
18                          USI              d013
2023-08-07 21:23:44,615:WARNING:
'xgboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install xgboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2023-08-07 21:23:44,616:WARNING:
'catboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install catboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2023-08-07 21:23:44,842:WARNING:
'xgboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install xgboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2023-08-07 21:23:44,842:WARNING:
'catboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install catboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2023-08-07 21:23:44,844:INFO:setup() successfully completed in 1.99s...............
2023-08-07 21:23:52,633:INFO:Initializing compare_models()
2023-08-07 21:23:52,634:INFO:compare_models(self=<pycaret.classification.oop.ClassificationExperiment object at 0x0000026E1839CA30>, include=None, fold=None, round=4, cross_validation=True, sort=Accuracy, n_select=1, budget_time=None, turbo=True, errors=ignore, fit_kwargs=None, groups=None, experiment_custom_tags=None, probability_threshold=None, verbose=True, parallel=None, caller_params={'self': <pycaret.classification.oop.ClassificationExperiment object at 0x0000026E1839CA30>, 'include': None, 'exclude': None, 'fold': None, 'round': 4, 'cross_validation': True, 'sort': 'Accuracy', 'n_select': 1, 'budget_time': None, 'turbo': True, 'errors': 'ignore', 'fit_kwargs': None, 'groups': None, 'experiment_custom_tags': None, 'probability_threshold': None, 'engine': None, 'verbose': True, 'parallel': None, '__class__': <class 'pycaret.classification.oop.ClassificationExperiment'>}, exclude=None)
2023-08-07 21:23:52,635:INFO:Checking exceptions
2023-08-07 21:23:52,646:INFO:Preparing display monitor
2023-08-07 21:23:52,710:INFO:Initializing Logistic Regression
2023-08-07 21:23:52,712:INFO:Total runtime is 1.88748041788737e-05 minutes
2023-08-07 21:23:52,719:INFO:SubProcess create_model() called ==================================
2023-08-07 21:23:52,720:INFO:Initializing create_model()
2023-08-07 21:23:52,720:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x0000026E1839CA30>, estimator=lr, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x0000026E183EF340>, model_only=True, return_train_score=False, kwargs={})
2023-08-07 21:23:52,720:INFO:Checking exceptions
2023-08-07 21:23:52,720:INFO:Importing libraries
2023-08-07 21:23:52,721:INFO:Copying training dataset
2023-08-07 21:23:52,730:INFO:Defining folds
2023-08-07 21:23:52,730:INFO:Declaring metric variables
2023-08-07 21:23:52,736:INFO:Importing untrained model
2023-08-07 21:23:52,746:INFO:Logistic Regression Imported successfully
2023-08-07 21:23:52,756:INFO:Starting cross validation
2023-08-07 21:23:52,758:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2023-08-07 21:24:12,324:INFO:Calculating mean and std
2023-08-07 21:24:12,328:INFO:Creating metrics dataframe
2023-08-07 21:24:12,664:INFO:Uploading results into container
2023-08-07 21:24:12,666:INFO:Uploading model into container now
2023-08-07 21:24:12,667:INFO:_master_model_container: 1
2023-08-07 21:24:12,668:INFO:_display_container: 2
2023-08-07 21:24:12,669:INFO:LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=1000,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=123, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)
2023-08-07 21:24:12,670:INFO:create_model() successfully completed......................................
2023-08-07 21:24:12,811:INFO:SubProcess create_model() end ==================================
2023-08-07 21:24:12,812:INFO:Creating metrics dataframe
2023-08-07 21:24:12,840:INFO:Initializing K Neighbors Classifier
2023-08-07 21:24:12,840:INFO:Total runtime is 0.33550000985463463 minutes
2023-08-07 21:24:12,850:INFO:SubProcess create_model() called ==================================
2023-08-07 21:24:12,851:INFO:Initializing create_model()
2023-08-07 21:24:12,852:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x0000026E1839CA30>, estimator=knn, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x0000026E183EF340>, model_only=True, return_train_score=False, kwargs={})
2023-08-07 21:24:12,852:INFO:Checking exceptions
2023-08-07 21:24:12,853:INFO:Importing libraries
2023-08-07 21:24:12,853:INFO:Copying training dataset
2023-08-07 21:24:12,865:INFO:Defining folds
2023-08-07 21:24:12,866:INFO:Declaring metric variables
2023-08-07 21:24:12,880:INFO:Importing untrained model
2023-08-07 21:24:12,892:INFO:K Neighbors Classifier Imported successfully
2023-08-07 21:24:12,919:INFO:Starting cross validation
2023-08-07 21:24:12,924:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2023-08-07 21:24:15,504:INFO:Calculating mean and std
2023-08-07 21:24:15,507:INFO:Creating metrics dataframe
2023-08-07 21:24:15,834:INFO:Uploading results into container
2023-08-07 21:24:15,837:INFO:Uploading model into container now
2023-08-07 21:24:15,838:INFO:_master_model_container: 2
2023-08-07 21:24:15,839:INFO:_display_container: 2
2023-08-07 21:24:15,840:INFO:KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=-1, n_neighbors=5, p=2,
                     weights='uniform')
2023-08-07 21:24:15,841:INFO:create_model() successfully completed......................................
2023-08-07 21:24:15,975:INFO:SubProcess create_model() end ==================================
2023-08-07 21:24:15,975:INFO:Creating metrics dataframe
2023-08-07 21:24:16,010:INFO:Initializing Naive Bayes
2023-08-07 21:24:16,011:INFO:Total runtime is 0.38834970792134604 minutes
2023-08-07 21:24:16,021:INFO:SubProcess create_model() called ==================================
2023-08-07 21:24:16,022:INFO:Initializing create_model()
2023-08-07 21:24:16,023:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x0000026E1839CA30>, estimator=nb, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x0000026E183EF340>, model_only=True, return_train_score=False, kwargs={})
2023-08-07 21:24:16,023:INFO:Checking exceptions
2023-08-07 21:24:16,024:INFO:Importing libraries
2023-08-07 21:24:16,024:INFO:Copying training dataset
2023-08-07 21:24:16,036:INFO:Defining folds
2023-08-07 21:24:16,036:INFO:Declaring metric variables
2023-08-07 21:24:16,049:INFO:Importing untrained model
2023-08-07 21:24:16,060:INFO:Naive Bayes Imported successfully
2023-08-07 21:24:16,087:INFO:Starting cross validation
2023-08-07 21:24:16,090:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2023-08-07 21:24:18,493:INFO:Calculating mean and std
2023-08-07 21:24:18,496:INFO:Creating metrics dataframe
2023-08-07 21:24:18,810:INFO:Uploading results into container
2023-08-07 21:24:18,812:INFO:Uploading model into container now
2023-08-07 21:24:18,814:INFO:_master_model_container: 3
2023-08-07 21:24:18,814:INFO:_display_container: 2
2023-08-07 21:24:18,815:INFO:GaussianNB(priors=None, var_smoothing=1e-09)
2023-08-07 21:24:18,816:INFO:create_model() successfully completed......................................
2023-08-07 21:24:18,953:INFO:SubProcess create_model() end ==================================
2023-08-07 21:24:18,955:INFO:Creating metrics dataframe
2023-08-07 21:24:18,983:INFO:Initializing Decision Tree Classifier
2023-08-07 21:24:18,984:INFO:Total runtime is 0.43788321812947595 minutes
2023-08-07 21:24:18,995:INFO:SubProcess create_model() called ==================================
2023-08-07 21:24:18,996:INFO:Initializing create_model()
2023-08-07 21:24:18,997:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x0000026E1839CA30>, estimator=dt, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x0000026E183EF340>, model_only=True, return_train_score=False, kwargs={})
2023-08-07 21:24:18,997:INFO:Checking exceptions
2023-08-07 21:24:18,998:INFO:Importing libraries
2023-08-07 21:24:18,998:INFO:Copying training dataset
2023-08-07 21:24:19,011:INFO:Defining folds
2023-08-07 21:24:19,012:INFO:Declaring metric variables
2023-08-07 21:24:19,023:INFO:Importing untrained model
2023-08-07 21:24:19,036:INFO:Decision Tree Classifier Imported successfully
2023-08-07 21:24:19,061:INFO:Starting cross validation
2023-08-07 21:24:19,066:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2023-08-07 21:24:21,524:INFO:Calculating mean and std
2023-08-07 21:24:21,528:INFO:Creating metrics dataframe
2023-08-07 21:24:21,860:INFO:Uploading results into container
2023-08-07 21:24:21,862:INFO:Uploading model into container now
2023-08-07 21:24:21,864:INFO:_master_model_container: 4
2023-08-07 21:24:21,864:INFO:_display_container: 2
2023-08-07 21:24:21,866:INFO:DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
                       max_depth=None, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_samples_leaf=1,
                       min_samples_split=2, min_weight_fraction_leaf=0.0,
                       random_state=123, splitter='best')
2023-08-07 21:24:21,867:INFO:create_model() successfully completed......................................
2023-08-07 21:24:22,004:INFO:SubProcess create_model() end ==================================
2023-08-07 21:24:22,005:INFO:Creating metrics dataframe
2023-08-07 21:24:22,038:INFO:Initializing SVM - Linear Kernel
2023-08-07 21:24:22,038:INFO:Total runtime is 0.48879896402359013 minutes
2023-08-07 21:24:22,050:INFO:SubProcess create_model() called ==================================
2023-08-07 21:24:22,051:INFO:Initializing create_model()
2023-08-07 21:24:22,051:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x0000026E1839CA30>, estimator=svm, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x0000026E183EF340>, model_only=True, return_train_score=False, kwargs={})
2023-08-07 21:24:22,052:INFO:Checking exceptions
2023-08-07 21:24:22,052:INFO:Importing libraries
2023-08-07 21:24:22,052:INFO:Copying training dataset
2023-08-07 21:24:22,066:INFO:Defining folds
2023-08-07 21:24:22,066:INFO:Declaring metric variables
2023-08-07 21:24:22,078:INFO:Importing untrained model
2023-08-07 21:24:22,091:INFO:SVM - Linear Kernel Imported successfully
2023-08-07 21:24:22,116:INFO:Starting cross validation
2023-08-07 21:24:22,120:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2023-08-07 21:24:22,408:WARNING:C:\Users\Sajjad Sindhi\AppData\Local\anaconda3\lib\site-packages\pycaret\internal\metrics.py:138: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "C:\Users\Sajjad Sindhi\AppData\Local\anaconda3\lib\site-packages\sklearn\metrics\_scorer.py", line 76, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Sajjad Sindhi\AppData\Local\anaconda3\lib\site-packages\pycaret\internal\metrics.py", line 130, in _score
    return super()._score(
  File "C:\Users\Sajjad Sindhi\AppData\Local\anaconda3\lib\site-packages\sklearn\metrics\_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "C:\Users\Sajjad Sindhi\AppData\Local\anaconda3\lib\site-packages\sklearn\metrics\_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
  File "C:\Users\Sajjad Sindhi\AppData\Local\anaconda3\lib\site-packages\pycaret\internal\pipeline.py", line 121, in __getattr__
    return getattr(self._final_estimator, name)
  File "C:\Users\Sajjad Sindhi\AppData\Local\anaconda3\lib\site-packages\sklearn\utils\_available_if.py", line 32, in __get__
    if not self.check(obj):
  File "C:\Users\Sajjad Sindhi\AppData\Local\anaconda3\lib\site-packages\sklearn\linear_model\_stochastic_gradient.py", line 1236, in _check_proba
    raise AttributeError(
AttributeError: probability estimates are not available for loss='hinge'

  warnings.warn(

2023-08-07 21:24:22,427:WARNING:C:\Users\Sajjad Sindhi\AppData\Local\anaconda3\lib\site-packages\pycaret\internal\metrics.py:138: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "C:\Users\Sajjad Sindhi\AppData\Local\anaconda3\lib\site-packages\sklearn\metrics\_scorer.py", line 76, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Sajjad Sindhi\AppData\Local\anaconda3\lib\site-packages\pycaret\internal\metrics.py", line 130, in _score
    return super()._score(
  File "C:\Users\Sajjad Sindhi\AppData\Local\anaconda3\lib\site-packages\sklearn\metrics\_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "C:\Users\Sajjad Sindhi\AppData\Local\anaconda3\lib\site-packages\sklearn\metrics\_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
  File "C:\Users\Sajjad Sindhi\AppData\Local\anaconda3\lib\site-packages\pycaret\internal\pipeline.py", line 121, in __getattr__
    return getattr(self._final_estimator, name)
  File "C:\Users\Sajjad Sindhi\AppData\Local\anaconda3\lib\site-packages\sklearn\utils\_available_if.py", line 32, in __get__
    if not self.check(obj):
  File "C:\Users\Sajjad Sindhi\AppData\Local\anaconda3\lib\site-packages\sklearn\linear_model\_stochastic_gradient.py", line 1236, in _check_proba
    raise AttributeError(
AttributeError: probability estimates are not available for loss='hinge'

  warnings.warn(

2023-08-07 21:24:22,441:WARNING:C:\Users\Sajjad Sindhi\AppData\Local\anaconda3\lib\site-packages\pycaret\internal\metrics.py:138: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "C:\Users\Sajjad Sindhi\AppData\Local\anaconda3\lib\site-packages\sklearn\metrics\_scorer.py", line 76, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Sajjad Sindhi\AppData\Local\anaconda3\lib\site-packages\pycaret\internal\metrics.py", line 130, in _score
    return super()._score(
  File "C:\Users\Sajjad Sindhi\AppData\Local\anaconda3\lib\site-packages\sklearn\metrics\_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "C:\Users\Sajjad Sindhi\AppData\Local\anaconda3\lib\site-packages\sklearn\metrics\_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
  File "C:\Users\Sajjad Sindhi\AppData\Local\anaconda3\lib\site-packages\pycaret\internal\pipeline.py", line 121, in __getattr__
    return getattr(self._final_estimator, name)
  File "C:\Users\Sajjad Sindhi\AppData\Local\anaconda3\lib\site-packages\sklearn\utils\_available_if.py", line 32, in __get__
    if not self.check(obj):
  File "C:\Users\Sajjad Sindhi\AppData\Local\anaconda3\lib\site-packages\sklearn\linear_model\_stochastic_gradient.py", line 1236, in _check_proba
    raise AttributeError(
AttributeError: probability estimates are not available for loss='hinge'

  warnings.warn(

2023-08-07 21:24:22,464:WARNING:C:\Users\Sajjad Sindhi\AppData\Local\anaconda3\lib\site-packages\pycaret\internal\metrics.py:138: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "C:\Users\Sajjad Sindhi\AppData\Local\anaconda3\lib\site-packages\sklearn\metrics\_scorer.py", line 76, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Sajjad Sindhi\AppData\Local\anaconda3\lib\site-packages\pycaret\internal\metrics.py", line 130, in _score
    return super()._score(
  File "C:\Users\Sajjad Sindhi\AppData\Local\anaconda3\lib\site-packages\sklearn\metrics\_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "C:\Users\Sajjad Sindhi\AppData\Local\anaconda3\lib\site-packages\sklearn\metrics\_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
  File "C:\Users\Sajjad Sindhi\AppData\Local\anaconda3\lib\site-packages\pycaret\internal\pipeline.py", line 121, in __getattr__
    return getattr(self._final_estimator, name)
  File "C:\Users\Sajjad Sindhi\AppData\Local\anaconda3\lib\site-packages\sklearn\utils\_available_if.py", line 32, in __get__
    if not self.check(obj):
  File "C:\Users\Sajjad Sindhi\AppData\Local\anaconda3\lib\site-packages\sklearn\linear_model\_stochastic_gradient.py", line 1236, in _check_proba
    raise AttributeError(
AttributeError: probability estimates are not available for loss='hinge'

  warnings.warn(

2023-08-07 21:24:22,478:WARNING:C:\Users\Sajjad Sindhi\AppData\Local\anaconda3\lib\site-packages\pycaret\internal\metrics.py:138: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "C:\Users\Sajjad Sindhi\AppData\Local\anaconda3\lib\site-packages\sklearn\metrics\_scorer.py", line 76, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Sajjad Sindhi\AppData\Local\anaconda3\lib\site-packages\pycaret\internal\metrics.py", line 130, in _score
    return super()._score(
  File "C:\Users\Sajjad Sindhi\AppData\Local\anaconda3\lib\site-packages\sklearn\metrics\_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "C:\Users\Sajjad Sindhi\AppData\Local\anaconda3\lib\site-packages\sklearn\metrics\_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
  File "C:\Users\Sajjad Sindhi\AppData\Local\anaconda3\lib\site-packages\pycaret\internal\pipeline.py", line 121, in __getattr__
    return getattr(self._final_estimator, name)
  File "C:\Users\Sajjad Sindhi\AppData\Local\anaconda3\lib\site-packages\sklearn\utils\_available_if.py", line 32, in __get__
    if not self.check(obj):
  File "C:\Users\Sajjad Sindhi\AppData\Local\anaconda3\lib\site-packages\sklearn\linear_model\_stochastic_gradient.py", line 1236, in _check_proba
    raise AttributeError(
AttributeError: probability estimates are not available for loss='hinge'

  warnings.warn(

2023-08-07 21:24:22,485:WARNING:C:\Users\Sajjad Sindhi\AppData\Local\anaconda3\lib\site-packages\pycaret\internal\metrics.py:138: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "C:\Users\Sajjad Sindhi\AppData\Local\anaconda3\lib\site-packages\sklearn\metrics\_scorer.py", line 76, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Sajjad Sindhi\AppData\Local\anaconda3\lib\site-packages\pycaret\internal\metrics.py", line 130, in _score
    return super()._score(
  File "C:\Users\Sajjad Sindhi\AppData\Local\anaconda3\lib\site-packages\sklearn\metrics\_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "C:\Users\Sajjad Sindhi\AppData\Local\anaconda3\lib\site-packages\sklearn\metrics\_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
  File "C:\Users\Sajjad Sindhi\AppData\Local\anaconda3\lib\site-packages\pycaret\internal\pipeline.py", line 121, in __getattr__
    return getattr(self._final_estimator, name)
  File "C:\Users\Sajjad Sindhi\AppData\Local\anaconda3\lib\site-packages\sklearn\utils\_available_if.py", line 32, in __get__
    if not self.check(obj):
  File "C:\Users\Sajjad Sindhi\AppData\Local\anaconda3\lib\site-packages\sklearn\linear_model\_stochastic_gradient.py", line 1236, in _check_proba
    raise AttributeError(
AttributeError: probability estimates are not available for loss='hinge'

  warnings.warn(

2023-08-07 21:24:22,497:WARNING:C:\Users\Sajjad Sindhi\AppData\Local\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

2023-08-07 21:24:22,526:WARNING:C:\Users\Sajjad Sindhi\AppData\Local\anaconda3\lib\site-packages\pycaret\internal\metrics.py:138: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "C:\Users\Sajjad Sindhi\AppData\Local\anaconda3\lib\site-packages\sklearn\metrics\_scorer.py", line 76, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Sajjad Sindhi\AppData\Local\anaconda3\lib\site-packages\pycaret\internal\metrics.py", line 130, in _score
    return super()._score(
  File "C:\Users\Sajjad Sindhi\AppData\Local\anaconda3\lib\site-packages\sklearn\metrics\_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "C:\Users\Sajjad Sindhi\AppData\Local\anaconda3\lib\site-packages\sklearn\metrics\_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
  File "C:\Users\Sajjad Sindhi\AppData\Local\anaconda3\lib\site-packages\pycaret\internal\pipeline.py", line 121, in __getattr__
    return getattr(self._final_estimator, name)
  File "C:\Users\Sajjad Sindhi\AppData\Local\anaconda3\lib\site-packages\sklearn\utils\_available_if.py", line 32, in __get__
    if not self.check(obj):
  File "C:\Users\Sajjad Sindhi\AppData\Local\anaconda3\lib\site-packages\sklearn\linear_model\_stochastic_gradient.py", line 1236, in _check_proba
    raise AttributeError(
AttributeError: probability estimates are not available for loss='hinge'

  warnings.warn(

2023-08-07 21:24:22,558:WARNING:C:\Users\Sajjad Sindhi\AppData\Local\anaconda3\lib\site-packages\pycaret\internal\metrics.py:138: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "C:\Users\Sajjad Sindhi\AppData\Local\anaconda3\lib\site-packages\sklearn\metrics\_scorer.py", line 76, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Sajjad Sindhi\AppData\Local\anaconda3\lib\site-packages\pycaret\internal\metrics.py", line 130, in _score
    return super()._score(
  File "C:\Users\Sajjad Sindhi\AppData\Local\anaconda3\lib\site-packages\sklearn\metrics\_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "C:\Users\Sajjad Sindhi\AppData\Local\anaconda3\lib\site-packages\sklearn\metrics\_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
  File "C:\Users\Sajjad Sindhi\AppData\Local\anaconda3\lib\site-packages\pycaret\internal\pipeline.py", line 121, in __getattr__
    return getattr(self._final_estimator, name)
  File "C:\Users\Sajjad Sindhi\AppData\Local\anaconda3\lib\site-packages\sklearn\utils\_available_if.py", line 32, in __get__
    if not self.check(obj):
  File "C:\Users\Sajjad Sindhi\AppData\Local\anaconda3\lib\site-packages\sklearn\linear_model\_stochastic_gradient.py", line 1236, in _check_proba
    raise AttributeError(
AttributeError: probability estimates are not available for loss='hinge'

  warnings.warn(

2023-08-07 21:24:22,576:WARNING:C:\Users\Sajjad Sindhi\AppData\Local\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

2023-08-07 21:24:22,973:WARNING:C:\Users\Sajjad Sindhi\AppData\Local\anaconda3\lib\site-packages\pycaret\internal\metrics.py:138: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "C:\Users\Sajjad Sindhi\AppData\Local\anaconda3\lib\site-packages\sklearn\metrics\_scorer.py", line 76, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Sajjad Sindhi\AppData\Local\anaconda3\lib\site-packages\pycaret\internal\metrics.py", line 130, in _score
    return super()._score(
  File "C:\Users\Sajjad Sindhi\AppData\Local\anaconda3\lib\site-packages\sklearn\metrics\_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "C:\Users\Sajjad Sindhi\AppData\Local\anaconda3\lib\site-packages\sklearn\metrics\_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
  File "C:\Users\Sajjad Sindhi\AppData\Local\anaconda3\lib\site-packages\pycaret\internal\pipeline.py", line 121, in __getattr__
    return getattr(self._final_estimator, name)
  File "C:\Users\Sajjad Sindhi\AppData\Local\anaconda3\lib\site-packages\sklearn\utils\_available_if.py", line 32, in __get__
    if not self.check(obj):
  File "C:\Users\Sajjad Sindhi\AppData\Local\anaconda3\lib\site-packages\sklearn\linear_model\_stochastic_gradient.py", line 1236, in _check_proba
    raise AttributeError(
AttributeError: probability estimates are not available for loss='hinge'

  warnings.warn(

2023-08-07 21:24:23,028:WARNING:C:\Users\Sajjad Sindhi\AppData\Local\anaconda3\lib\site-packages\pycaret\internal\metrics.py:138: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "C:\Users\Sajjad Sindhi\AppData\Local\anaconda3\lib\site-packages\sklearn\metrics\_scorer.py", line 76, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Sajjad Sindhi\AppData\Local\anaconda3\lib\site-packages\pycaret\internal\metrics.py", line 130, in _score
    return super()._score(
  File "C:\Users\Sajjad Sindhi\AppData\Local\anaconda3\lib\site-packages\sklearn\metrics\_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "C:\Users\Sajjad Sindhi\AppData\Local\anaconda3\lib\site-packages\sklearn\metrics\_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
  File "C:\Users\Sajjad Sindhi\AppData\Local\anaconda3\lib\site-packages\pycaret\internal\pipeline.py", line 121, in __getattr__
    return getattr(self._final_estimator, name)
  File "C:\Users\Sajjad Sindhi\AppData\Local\anaconda3\lib\site-packages\sklearn\utils\_available_if.py", line 32, in __get__
    if not self.check(obj):
  File "C:\Users\Sajjad Sindhi\AppData\Local\anaconda3\lib\site-packages\sklearn\linear_model\_stochastic_gradient.py", line 1236, in _check_proba
    raise AttributeError(
AttributeError: probability estimates are not available for loss='hinge'

  warnings.warn(

2023-08-07 21:24:24,474:INFO:Calculating mean and std
2023-08-07 21:24:24,478:INFO:Creating metrics dataframe
2023-08-07 21:24:24,814:INFO:Uploading results into container
2023-08-07 21:24:24,816:INFO:Uploading model into container now
2023-08-07 21:24:24,817:INFO:_master_model_container: 5
2023-08-07 21:24:24,818:INFO:_display_container: 2
2023-08-07 21:24:24,820:INFO:SGDClassifier(alpha=0.0001, average=False, class_weight=None,
              early_stopping=False, epsilon=0.1, eta0=0.001, fit_intercept=True,
              l1_ratio=0.15, learning_rate='optimal', loss='hinge',
              max_iter=1000, n_iter_no_change=5, n_jobs=-1, penalty='l2',
              power_t=0.5, random_state=123, shuffle=True, tol=0.001,
              validation_fraction=0.1, verbose=0, warm_start=False)
2023-08-07 21:24:24,820:INFO:create_model() successfully completed......................................
2023-08-07 21:24:24,955:INFO:SubProcess create_model() end ==================================
2023-08-07 21:24:24,955:INFO:Creating metrics dataframe
2023-08-07 21:24:24,989:INFO:Initializing Ridge Classifier
2023-08-07 21:24:24,989:INFO:Total runtime is 0.5379831234614055 minutes
2023-08-07 21:24:24,999:INFO:SubProcess create_model() called ==================================
2023-08-07 21:24:25,000:INFO:Initializing create_model()
2023-08-07 21:24:25,001:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x0000026E1839CA30>, estimator=ridge, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x0000026E183EF340>, model_only=True, return_train_score=False, kwargs={})
2023-08-07 21:24:25,001:INFO:Checking exceptions
2023-08-07 21:24:25,002:INFO:Importing libraries
2023-08-07 21:24:25,002:INFO:Copying training dataset
2023-08-07 21:24:25,016:INFO:Defining folds
2023-08-07 21:24:25,017:INFO:Declaring metric variables
2023-08-07 21:24:25,027:INFO:Importing untrained model
2023-08-07 21:24:25,039:INFO:Ridge Classifier Imported successfully
2023-08-07 21:24:25,060:INFO:Starting cross validation
2023-08-07 21:24:25,062:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2023-08-07 21:24:25,349:WARNING:C:\Users\Sajjad Sindhi\AppData\Local\anaconda3\lib\site-packages\pycaret\internal\metrics.py:138: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "C:\Users\Sajjad Sindhi\AppData\Local\anaconda3\lib\site-packages\sklearn\metrics\_scorer.py", line 76, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Sajjad Sindhi\AppData\Local\anaconda3\lib\site-packages\pycaret\internal\metrics.py", line 130, in _score
    return super()._score(
  File "C:\Users\Sajjad Sindhi\AppData\Local\anaconda3\lib\site-packages\sklearn\metrics\_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "C:\Users\Sajjad Sindhi\AppData\Local\anaconda3\lib\site-packages\sklearn\metrics\_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
  File "C:\Users\Sajjad Sindhi\AppData\Local\anaconda3\lib\site-packages\pycaret\internal\pipeline.py", line 121, in __getattr__
    return getattr(self._final_estimator, name)
AttributeError: 'RidgeClassifier' object has no attribute 'predict_proba'

  warnings.warn(

2023-08-07 21:24:25,367:WARNING:C:\Users\Sajjad Sindhi\AppData\Local\anaconda3\lib\site-packages\pycaret\internal\metrics.py:138: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "C:\Users\Sajjad Sindhi\AppData\Local\anaconda3\lib\site-packages\sklearn\metrics\_scorer.py", line 76, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Sajjad Sindhi\AppData\Local\anaconda3\lib\site-packages\pycaret\internal\metrics.py", line 130, in _score
    return super()._score(
  File "C:\Users\Sajjad Sindhi\AppData\Local\anaconda3\lib\site-packages\sklearn\metrics\_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "C:\Users\Sajjad Sindhi\AppData\Local\anaconda3\lib\site-packages\sklearn\metrics\_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
  File "C:\Users\Sajjad Sindhi\AppData\Local\anaconda3\lib\site-packages\pycaret\internal\pipeline.py", line 121, in __getattr__
    return getattr(self._final_estimator, name)
AttributeError: 'RidgeClassifier' object has no attribute 'predict_proba'

  warnings.warn(

2023-08-07 21:24:25,394:WARNING:C:\Users\Sajjad Sindhi\AppData\Local\anaconda3\lib\site-packages\pycaret\internal\metrics.py:138: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "C:\Users\Sajjad Sindhi\AppData\Local\anaconda3\lib\site-packages\sklearn\metrics\_scorer.py", line 76, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Sajjad Sindhi\AppData\Local\anaconda3\lib\site-packages\pycaret\internal\metrics.py", line 130, in _score
    return super()._score(
  File "C:\Users\Sajjad Sindhi\AppData\Local\anaconda3\lib\site-packages\sklearn\metrics\_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "C:\Users\Sajjad Sindhi\AppData\Local\anaconda3\lib\site-packages\sklearn\metrics\_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
  File "C:\Users\Sajjad Sindhi\AppData\Local\anaconda3\lib\site-packages\pycaret\internal\pipeline.py", line 121, in __getattr__
    return getattr(self._final_estimator, name)
AttributeError: 'RidgeClassifier' object has no attribute 'predict_proba'

  warnings.warn(

2023-08-07 21:24:25,428:WARNING:C:\Users\Sajjad Sindhi\AppData\Local\anaconda3\lib\site-packages\pycaret\internal\metrics.py:138: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "C:\Users\Sajjad Sindhi\AppData\Local\anaconda3\lib\site-packages\sklearn\metrics\_scorer.py", line 76, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Sajjad Sindhi\AppData\Local\anaconda3\lib\site-packages\pycaret\internal\metrics.py", line 130, in _score
    return super()._score(
  File "C:\Users\Sajjad Sindhi\AppData\Local\anaconda3\lib\site-packages\sklearn\metrics\_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "C:\Users\Sajjad Sindhi\AppData\Local\anaconda3\lib\site-packages\sklearn\metrics\_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
  File "C:\Users\Sajjad Sindhi\AppData\Local\anaconda3\lib\site-packages\pycaret\internal\pipeline.py", line 121, in __getattr__
    return getattr(self._final_estimator, name)
AttributeError: 'RidgeClassifier' object has no attribute 'predict_proba'

  warnings.warn(

2023-08-07 21:24:25,430:WARNING:C:\Users\Sajjad Sindhi\AppData\Local\anaconda3\lib\site-packages\pycaret\internal\metrics.py:138: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "C:\Users\Sajjad Sindhi\AppData\Local\anaconda3\lib\site-packages\sklearn\metrics\_scorer.py", line 76, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Sajjad Sindhi\AppData\Local\anaconda3\lib\site-packages\pycaret\internal\metrics.py", line 130, in _score
    return super()._score(
  File "C:\Users\Sajjad Sindhi\AppData\Local\anaconda3\lib\site-packages\sklearn\metrics\_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "C:\Users\Sajjad Sindhi\AppData\Local\anaconda3\lib\site-packages\sklearn\metrics\_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
  File "C:\Users\Sajjad Sindhi\AppData\Local\anaconda3\lib\site-packages\pycaret\internal\pipeline.py", line 121, in __getattr__
    return getattr(self._final_estimator, name)
AttributeError: 'RidgeClassifier' object has no attribute 'predict_proba'

  warnings.warn(

2023-08-07 21:24:25,439:WARNING:C:\Users\Sajjad Sindhi\AppData\Local\anaconda3\lib\site-packages\pycaret\internal\metrics.py:138: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "C:\Users\Sajjad Sindhi\AppData\Local\anaconda3\lib\site-packages\sklearn\metrics\_scorer.py", line 76, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Sajjad Sindhi\AppData\Local\anaconda3\lib\site-packages\pycaret\internal\metrics.py", line 130, in _score
    return super()._score(
  File "C:\Users\Sajjad Sindhi\AppData\Local\anaconda3\lib\site-packages\sklearn\metrics\_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "C:\Users\Sajjad Sindhi\AppData\Local\anaconda3\lib\site-packages\sklearn\metrics\_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
  File "C:\Users\Sajjad Sindhi\AppData\Local\anaconda3\lib\site-packages\pycaret\internal\pipeline.py", line 121, in __getattr__
    return getattr(self._final_estimator, name)
AttributeError: 'RidgeClassifier' object has no attribute 'predict_proba'

  warnings.warn(

2023-08-07 21:24:25,460:WARNING:C:\Users\Sajjad Sindhi\AppData\Local\anaconda3\lib\site-packages\pycaret\internal\metrics.py:138: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "C:\Users\Sajjad Sindhi\AppData\Local\anaconda3\lib\site-packages\sklearn\metrics\_scorer.py", line 76, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Sajjad Sindhi\AppData\Local\anaconda3\lib\site-packages\pycaret\internal\metrics.py", line 130, in _score
    return super()._score(
  File "C:\Users\Sajjad Sindhi\AppData\Local\anaconda3\lib\site-packages\sklearn\metrics\_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "C:\Users\Sajjad Sindhi\AppData\Local\anaconda3\lib\site-packages\sklearn\metrics\_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
  File "C:\Users\Sajjad Sindhi\AppData\Local\anaconda3\lib\site-packages\pycaret\internal\pipeline.py", line 121, in __getattr__
    return getattr(self._final_estimator, name)
AttributeError: 'RidgeClassifier' object has no attribute 'predict_proba'

  warnings.warn(

2023-08-07 21:24:25,948:WARNING:C:\Users\Sajjad Sindhi\AppData\Local\anaconda3\lib\site-packages\pycaret\internal\metrics.py:138: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "C:\Users\Sajjad Sindhi\AppData\Local\anaconda3\lib\site-packages\sklearn\metrics\_scorer.py", line 76, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Sajjad Sindhi\AppData\Local\anaconda3\lib\site-packages\pycaret\internal\metrics.py", line 130, in _score
    return super()._score(
  File "C:\Users\Sajjad Sindhi\AppData\Local\anaconda3\lib\site-packages\sklearn\metrics\_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "C:\Users\Sajjad Sindhi\AppData\Local\anaconda3\lib\site-packages\sklearn\metrics\_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
  File "C:\Users\Sajjad Sindhi\AppData\Local\anaconda3\lib\site-packages\pycaret\internal\pipeline.py", line 121, in __getattr__
    return getattr(self._final_estimator, name)
AttributeError: 'RidgeClassifier' object has no attribute 'predict_proba'

  warnings.warn(

2023-08-07 21:24:25,989:WARNING:C:\Users\Sajjad Sindhi\AppData\Local\anaconda3\lib\site-packages\pycaret\internal\metrics.py:138: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "C:\Users\Sajjad Sindhi\AppData\Local\anaconda3\lib\site-packages\sklearn\metrics\_scorer.py", line 76, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Sajjad Sindhi\AppData\Local\anaconda3\lib\site-packages\pycaret\internal\metrics.py", line 130, in _score
    return super()._score(
  File "C:\Users\Sajjad Sindhi\AppData\Local\anaconda3\lib\site-packages\sklearn\metrics\_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "C:\Users\Sajjad Sindhi\AppData\Local\anaconda3\lib\site-packages\sklearn\metrics\_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
  File "C:\Users\Sajjad Sindhi\AppData\Local\anaconda3\lib\site-packages\pycaret\internal\pipeline.py", line 121, in __getattr__
    return getattr(self._final_estimator, name)
AttributeError: 'RidgeClassifier' object has no attribute 'predict_proba'

  warnings.warn(

2023-08-07 21:24:27,482:INFO:Calculating mean and std
2023-08-07 21:24:27,486:INFO:Creating metrics dataframe
2023-08-07 21:24:27,814:INFO:Uploading results into container
2023-08-07 21:24:27,816:INFO:Uploading model into container now
2023-08-07 21:24:27,817:INFO:_master_model_container: 6
2023-08-07 21:24:27,818:INFO:_display_container: 2
2023-08-07 21:24:27,819:INFO:RidgeClassifier(alpha=1.0, class_weight=None, copy_X=True, fit_intercept=True,
                max_iter=None, positive=False, random_state=123, solver='auto',
                tol=0.0001)
2023-08-07 21:24:27,820:INFO:create_model() successfully completed......................................
2023-08-07 21:24:27,960:INFO:SubProcess create_model() end ==================================
2023-08-07 21:24:27,961:INFO:Creating metrics dataframe
2023-08-07 21:24:27,991:INFO:Initializing Random Forest Classifier
2023-08-07 21:24:27,991:INFO:Total runtime is 0.5880156636238099 minutes
2023-08-07 21:24:28,003:INFO:SubProcess create_model() called ==================================
2023-08-07 21:24:28,004:INFO:Initializing create_model()
2023-08-07 21:24:28,005:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x0000026E1839CA30>, estimator=rf, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x0000026E183EF340>, model_only=True, return_train_score=False, kwargs={})
2023-08-07 21:24:28,005:INFO:Checking exceptions
2023-08-07 21:24:28,006:INFO:Importing libraries
2023-08-07 21:24:28,007:INFO:Copying training dataset
2023-08-07 21:24:28,017:INFO:Defining folds
2023-08-07 21:24:28,018:INFO:Declaring metric variables
2023-08-07 21:24:28,031:INFO:Importing untrained model
2023-08-07 21:24:28,042:INFO:Random Forest Classifier Imported successfully
2023-08-07 21:24:28,064:INFO:Starting cross validation
2023-08-07 21:24:28,069:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2023-08-07 21:24:31,606:INFO:Calculating mean and std
2023-08-07 21:24:31,610:INFO:Creating metrics dataframe
2023-08-07 21:24:31,943:INFO:Uploading results into container
2023-08-07 21:24:31,945:INFO:Uploading model into container now
2023-08-07 21:24:31,946:INFO:_master_model_container: 7
2023-08-07 21:24:31,947:INFO:_display_container: 2
2023-08-07 21:24:31,949:INFO:RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='sqrt',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_samples_leaf=1,
                       min_samples_split=2, min_weight_fraction_leaf=0.0,
                       n_estimators=100, n_jobs=-1, oob_score=False,
                       random_state=123, verbose=0, warm_start=False)
2023-08-07 21:24:31,950:INFO:create_model() successfully completed......................................
2023-08-07 21:24:32,086:INFO:SubProcess create_model() end ==================================
2023-08-07 21:24:32,086:INFO:Creating metrics dataframe
2023-08-07 21:24:32,121:INFO:Initializing Quadratic Discriminant Analysis
2023-08-07 21:24:32,121:INFO:Total runtime is 0.6568490505218506 minutes
2023-08-07 21:24:32,133:INFO:SubProcess create_model() called ==================================
2023-08-07 21:24:32,134:INFO:Initializing create_model()
2023-08-07 21:24:32,135:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x0000026E1839CA30>, estimator=qda, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x0000026E183EF340>, model_only=True, return_train_score=False, kwargs={})
2023-08-07 21:24:32,135:INFO:Checking exceptions
2023-08-07 21:24:32,136:INFO:Importing libraries
2023-08-07 21:24:32,136:INFO:Copying training dataset
2023-08-07 21:24:32,149:INFO:Defining folds
2023-08-07 21:24:32,150:INFO:Declaring metric variables
2023-08-07 21:24:32,163:INFO:Importing untrained model
2023-08-07 21:24:32,175:INFO:Quadratic Discriminant Analysis Imported successfully
2023-08-07 21:24:32,200:INFO:Starting cross validation
2023-08-07 21:24:32,204:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2023-08-07 21:24:34,618:INFO:Calculating mean and std
2023-08-07 21:24:34,622:INFO:Creating metrics dataframe
2023-08-07 21:24:34,954:INFO:Uploading results into container
2023-08-07 21:24:34,956:INFO:Uploading model into container now
2023-08-07 21:24:34,957:INFO:_master_model_container: 8
2023-08-07 21:24:34,958:INFO:_display_container: 2
2023-08-07 21:24:34,959:INFO:QuadraticDiscriminantAnalysis(priors=None, reg_param=0.0,
                              store_covariance=False, tol=0.0001)
2023-08-07 21:24:34,960:INFO:create_model() successfully completed......................................
2023-08-07 21:24:35,098:INFO:SubProcess create_model() end ==================================
2023-08-07 21:24:35,099:INFO:Creating metrics dataframe
2023-08-07 21:24:35,132:INFO:Initializing Ada Boost Classifier
2023-08-07 21:24:35,133:INFO:Total runtime is 0.7070343375205994 minutes
2023-08-07 21:24:35,142:INFO:SubProcess create_model() called ==================================
2023-08-07 21:24:35,144:INFO:Initializing create_model()
2023-08-07 21:24:35,144:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x0000026E1839CA30>, estimator=ada, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x0000026E183EF340>, model_only=True, return_train_score=False, kwargs={})
2023-08-07 21:24:35,145:INFO:Checking exceptions
2023-08-07 21:24:35,145:INFO:Importing libraries
2023-08-07 21:24:35,145:INFO:Copying training dataset
2023-08-07 21:24:35,162:INFO:Defining folds
2023-08-07 21:24:35,163:INFO:Declaring metric variables
2023-08-07 21:24:35,174:INFO:Importing untrained model
2023-08-07 21:24:35,185:INFO:Ada Boost Classifier Imported successfully
2023-08-07 21:24:35,217:INFO:Starting cross validation
2023-08-07 21:24:35,221:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2023-08-07 21:24:38,224:INFO:Calculating mean and std
2023-08-07 21:24:38,228:INFO:Creating metrics dataframe
2023-08-07 21:24:38,561:INFO:Uploading results into container
2023-08-07 21:24:38,563:INFO:Uploading model into container now
2023-08-07 21:24:38,565:INFO:_master_model_container: 9
2023-08-07 21:24:38,565:INFO:_display_container: 2
2023-08-07 21:24:38,567:INFO:AdaBoostClassifier(algorithm='SAMME.R', base_estimator='deprecated',
                   estimator=None, learning_rate=1.0, n_estimators=50,
                   random_state=123)
2023-08-07 21:24:38,567:INFO:create_model() successfully completed......................................
2023-08-07 21:24:38,702:INFO:SubProcess create_model() end ==================================
2023-08-07 21:24:38,702:INFO:Creating metrics dataframe
2023-08-07 21:24:38,738:INFO:Initializing Gradient Boosting Classifier
2023-08-07 21:24:38,738:INFO:Total runtime is 0.7671184579531353 minutes
2023-08-07 21:24:38,750:INFO:SubProcess create_model() called ==================================
2023-08-07 21:24:38,751:INFO:Initializing create_model()
2023-08-07 21:24:38,752:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x0000026E1839CA30>, estimator=gbc, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x0000026E183EF340>, model_only=True, return_train_score=False, kwargs={})
2023-08-07 21:24:38,752:INFO:Checking exceptions
2023-08-07 21:24:38,753:INFO:Importing libraries
2023-08-07 21:24:38,753:INFO:Copying training dataset
2023-08-07 21:24:38,766:INFO:Defining folds
2023-08-07 21:24:38,766:INFO:Declaring metric variables
2023-08-07 21:24:38,779:INFO:Importing untrained model
2023-08-07 21:24:38,790:INFO:Gradient Boosting Classifier Imported successfully
2023-08-07 21:24:38,816:INFO:Starting cross validation
2023-08-07 21:24:38,821:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2023-08-07 21:24:41,866:INFO:Calculating mean and std
2023-08-07 21:24:41,870:INFO:Creating metrics dataframe
2023-08-07 21:24:42,088:INFO:Uploading results into container
2023-08-07 21:24:42,090:INFO:Uploading model into container now
2023-08-07 21:24:42,092:INFO:_master_model_container: 10
2023-08-07 21:24:42,092:INFO:_display_container: 2
2023-08-07 21:24:42,094:INFO:GradientBoostingClassifier(ccp_alpha=0.0, criterion='friedman_mse', init=None,
                           learning_rate=0.1, loss='log_loss', max_depth=3,
                           max_features=None, max_leaf_nodes=None,
                           min_impurity_decrease=0.0, min_samples_leaf=1,
                           min_samples_split=2, min_weight_fraction_leaf=0.0,
                           n_estimators=100, n_iter_no_change=None,
                           random_state=123, subsample=1.0, tol=0.0001,
                           validation_fraction=0.1, verbose=0,
                           warm_start=False)
2023-08-07 21:24:42,094:INFO:create_model() successfully completed......................................
2023-08-07 21:24:42,212:INFO:SubProcess create_model() end ==================================
2023-08-07 21:24:42,212:INFO:Creating metrics dataframe
2023-08-07 21:24:42,236:INFO:Initializing Linear Discriminant Analysis
2023-08-07 21:24:42,237:INFO:Total runtime is 0.8254343628883363 minutes
2023-08-07 21:24:42,253:INFO:SubProcess create_model() called ==================================
2023-08-07 21:24:42,254:INFO:Initializing create_model()
2023-08-07 21:24:42,255:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x0000026E1839CA30>, estimator=lda, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x0000026E183EF340>, model_only=True, return_train_score=False, kwargs={})
2023-08-07 21:24:42,255:INFO:Checking exceptions
2023-08-07 21:24:42,256:INFO:Importing libraries
2023-08-07 21:24:42,256:INFO:Copying training dataset
2023-08-07 21:24:42,276:INFO:Defining folds
2023-08-07 21:24:42,277:INFO:Declaring metric variables
2023-08-07 21:24:42,288:INFO:Importing untrained model
2023-08-07 21:24:42,303:INFO:Linear Discriminant Analysis Imported successfully
2023-08-07 21:24:42,324:INFO:Starting cross validation
2023-08-07 21:24:42,328:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2023-08-07 21:24:44,309:INFO:Calculating mean and std
2023-08-07 21:24:44,311:INFO:Creating metrics dataframe
2023-08-07 21:24:44,628:INFO:Uploading results into container
2023-08-07 21:24:44,629:INFO:Uploading model into container now
2023-08-07 21:24:44,630:INFO:_master_model_container: 11
2023-08-07 21:24:44,630:INFO:_display_container: 2
2023-08-07 21:24:44,631:INFO:LinearDiscriminantAnalysis(covariance_estimator=None, n_components=None,
                           priors=None, shrinkage=None, solver='svd',
                           store_covariance=False, tol=0.0001)
2023-08-07 21:24:44,631:INFO:create_model() successfully completed......................................
2023-08-07 21:24:44,746:INFO:SubProcess create_model() end ==================================
2023-08-07 21:24:44,747:INFO:Creating metrics dataframe
2023-08-07 21:24:44,787:INFO:Initializing Extra Trees Classifier
2023-08-07 21:24:44,787:INFO:Total runtime is 0.867934290568034 minutes
2023-08-07 21:24:44,801:INFO:SubProcess create_model() called ==================================
2023-08-07 21:24:44,802:INFO:Initializing create_model()
2023-08-07 21:24:44,802:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x0000026E1839CA30>, estimator=et, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x0000026E183EF340>, model_only=True, return_train_score=False, kwargs={})
2023-08-07 21:24:44,803:INFO:Checking exceptions
2023-08-07 21:24:44,803:INFO:Importing libraries
2023-08-07 21:24:44,803:INFO:Copying training dataset
2023-08-07 21:24:44,823:INFO:Defining folds
2023-08-07 21:24:44,824:INFO:Declaring metric variables
2023-08-07 21:24:44,839:INFO:Importing untrained model
2023-08-07 21:24:44,852:INFO:Extra Trees Classifier Imported successfully
2023-08-07 21:24:44,881:INFO:Starting cross validation
2023-08-07 21:24:44,886:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2023-08-07 21:24:48,876:WARNING:C:\Users\Sajjad Sindhi\AppData\Local\anaconda3\lib\site-packages\pycaret\internal\pipeline.py:319: UserWarning: Persisting input arguments took 1.38s to run.If this happens often in your code, it can cause performance problems (results will be correct in all cases). The reason for this is probably some large input arguments for a wrapped function.
  X, _ = self._memory_full_transform(self, X, None, with_final=False)

2023-08-07 21:24:50,667:WARNING:C:\Users\Sajjad Sindhi\AppData\Local\anaconda3\lib\site-packages\pycaret\internal\pipeline.py:310: UserWarning: Persisting input arguments took 1.13s to run.If this happens often in your code, it can cause performance problems (results will be correct in all cases). The reason for this is probably some large input arguments for a wrapped function.
  X, _ = self._memory_full_transform(self, X, None, with_final=False)

2023-08-07 21:24:50,673:WARNING:C:\Users\Sajjad Sindhi\AppData\Local\anaconda3\lib\site-packages\pycaret\internal\pipeline.py:310: UserWarning: Persisting input arguments took 1.12s to run.If this happens often in your code, it can cause performance problems (results will be correct in all cases). The reason for this is probably some large input arguments for a wrapped function.
  X, _ = self._memory_full_transform(self, X, None, with_final=False)

2023-08-07 21:24:51,942:INFO:Calculating mean and std
2023-08-07 21:24:51,945:INFO:Creating metrics dataframe
2023-08-07 21:24:52,182:INFO:Uploading results into container
2023-08-07 21:24:52,183:INFO:Uploading model into container now
2023-08-07 21:24:52,184:INFO:_master_model_container: 12
2023-08-07 21:24:52,185:INFO:_display_container: 2
2023-08-07 21:24:52,193:INFO:ExtraTreesClassifier(bootstrap=False, ccp_alpha=0.0, class_weight=None,
                     criterion='gini', max_depth=None, max_features='sqrt',
                     max_leaf_nodes=None, max_samples=None,
                     min_impurity_decrease=0.0, min_samples_leaf=1,
                     min_samples_split=2, min_weight_fraction_leaf=0.0,
                     n_estimators=100, n_jobs=-1, oob_score=False,
                     random_state=123, verbose=0, warm_start=False)
2023-08-07 21:24:52,194:INFO:create_model() successfully completed......................................
2023-08-07 21:24:52,347:INFO:SubProcess create_model() end ==================================
2023-08-07 21:24:52,347:INFO:Creating metrics dataframe
2023-08-07 21:24:52,396:INFO:Initializing Light Gradient Boosting Machine
2023-08-07 21:24:52,396:INFO:Total runtime is 0.9947660406430563 minutes
2023-08-07 21:24:52,405:INFO:SubProcess create_model() called ==================================
2023-08-07 21:24:52,407:INFO:Initializing create_model()
2023-08-07 21:24:52,407:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x0000026E1839CA30>, estimator=lightgbm, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x0000026E183EF340>, model_only=True, return_train_score=False, kwargs={})
2023-08-07 21:24:52,407:INFO:Checking exceptions
2023-08-07 21:24:52,408:INFO:Importing libraries
2023-08-07 21:24:52,408:INFO:Copying training dataset
2023-08-07 21:24:52,424:INFO:Defining folds
2023-08-07 21:24:52,424:INFO:Declaring metric variables
2023-08-07 21:24:52,436:INFO:Importing untrained model
2023-08-07 21:24:52,446:INFO:Light Gradient Boosting Machine Imported successfully
2023-08-07 21:24:52,466:INFO:Starting cross validation
2023-08-07 21:24:52,471:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2023-08-07 21:24:52,812:WARNING:C:\Users\Sajjad Sindhi\AppData\Local\anaconda3\lib\site-packages\sklearn\base.py:299: UserWarning: Trying to unpickle estimator LabelEncoder from version 1.2.2 when using version 1.2.1. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/model_persistence.html#security-maintainability-limitations
  warnings.warn(

2023-08-07 21:24:52,912:WARNING:C:\Users\Sajjad Sindhi\AppData\Local\anaconda3\lib\site-packages\sklearn\base.py:299: UserWarning: Trying to unpickle estimator LabelEncoder from version 1.2.2 when using version 1.2.1. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/model_persistence.html#security-maintainability-limitations
  warnings.warn(

2023-08-07 21:24:52,931:WARNING:C:\Users\Sajjad Sindhi\AppData\Local\anaconda3\lib\site-packages\sklearn\base.py:299: UserWarning: Trying to unpickle estimator LabelEncoder from version 1.2.2 when using version 1.2.1. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/model_persistence.html#security-maintainability-limitations
  warnings.warn(

2023-08-07 21:24:52,967:WARNING:C:\Users\Sajjad Sindhi\AppData\Local\anaconda3\lib\site-packages\sklearn\base.py:299: UserWarning: Trying to unpickle estimator LabelEncoder from version 1.2.2 when using version 1.2.1. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/model_persistence.html#security-maintainability-limitations
  warnings.warn(

2023-08-07 21:24:53,045:WARNING:C:\Users\Sajjad Sindhi\AppData\Local\anaconda3\lib\site-packages\sklearn\base.py:299: UserWarning: Trying to unpickle estimator LabelEncoder from version 1.2.2 when using version 1.2.1. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/model_persistence.html#security-maintainability-limitations
  warnings.warn(

2023-08-07 21:24:53,043:WARNING:C:\Users\Sajjad Sindhi\AppData\Local\anaconda3\lib\site-packages\sklearn\base.py:299: UserWarning: Trying to unpickle estimator LabelEncoder from version 1.2.2 when using version 1.2.1. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/model_persistence.html#security-maintainability-limitations
  warnings.warn(

2023-08-07 21:24:53,112:WARNING:C:\Users\Sajjad Sindhi\AppData\Local\anaconda3\lib\site-packages\sklearn\base.py:299: UserWarning: Trying to unpickle estimator LabelEncoder from version 1.2.2 when using version 1.2.1. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/model_persistence.html#security-maintainability-limitations
  warnings.warn(

2023-08-07 21:24:53,114:WARNING:C:\Users\Sajjad Sindhi\AppData\Local\anaconda3\lib\site-packages\sklearn\base.py:299: UserWarning: Trying to unpickle estimator LabelEncoder from version 1.2.2 when using version 1.2.1. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/model_persistence.html#security-maintainability-limitations
  warnings.warn(

2023-08-07 21:24:53,688:WARNING:C:\Users\Sajjad Sindhi\AppData\Local\anaconda3\lib\site-packages\pycaret\internal\pipeline.py:310: UserWarning: Persisting input arguments took 0.57s to run.If this happens often in your code, it can cause performance problems (results will be correct in all cases). The reason for this is probably some large input arguments for a wrapped function.
  X, _ = self._memory_full_transform(self, X, None, with_final=False)

2023-08-07 21:24:53,811:WARNING:C:\Users\Sajjad Sindhi\AppData\Local\anaconda3\lib\site-packages\pycaret\internal\pipeline.py:310: UserWarning: Persisting input arguments took 0.56s to run.If this happens often in your code, it can cause performance problems (results will be correct in all cases). The reason for this is probably some large input arguments for a wrapped function.
  X, _ = self._memory_full_transform(self, X, None, with_final=False)

2023-08-07 21:24:54,033:WARNING:C:\Users\Sajjad Sindhi\AppData\Local\anaconda3\lib\site-packages\pycaret\internal\pipeline.py:310: UserWarning: Persisting input arguments took 0.67s to run.If this happens often in your code, it can cause performance problems (results will be correct in all cases). The reason for this is probably some large input arguments for a wrapped function.
  X, _ = self._memory_full_transform(self, X, None, with_final=False)

2023-08-07 21:24:54,037:WARNING:C:\Users\Sajjad Sindhi\AppData\Local\anaconda3\lib\site-packages\pycaret\internal\pipeline.py:310: UserWarning: Persisting input arguments took 0.69s to run.If this happens often in your code, it can cause performance problems (results will be correct in all cases). The reason for this is probably some large input arguments for a wrapped function.
  X, _ = self._memory_full_transform(self, X, None, with_final=False)

2023-08-07 21:24:54,107:WARNING:C:\Users\Sajjad Sindhi\AppData\Local\anaconda3\lib\site-packages\pycaret\internal\pipeline.py:310: UserWarning: Persisting input arguments took 0.70s to run.If this happens often in your code, it can cause performance problems (results will be correct in all cases). The reason for this is probably some large input arguments for a wrapped function.
  X, _ = self._memory_full_transform(self, X, None, with_final=False)

2023-08-07 21:24:55,202:WARNING:C:\Users\Sajjad Sindhi\AppData\Local\anaconda3\lib\site-packages\sklearn\base.py:299: UserWarning: Trying to unpickle estimator LabelEncoder from version 1.2.2 when using version 1.2.1. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/model_persistence.html#security-maintainability-limitations
  warnings.warn(

2023-08-07 21:24:55,432:WARNING:C:\Users\Sajjad Sindhi\AppData\Local\anaconda3\lib\site-packages\sklearn\base.py:299: UserWarning: Trying to unpickle estimator LabelEncoder from version 1.2.2 when using version 1.2.1. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/model_persistence.html#security-maintainability-limitations
  warnings.warn(

2023-08-07 21:24:56,826:INFO:Calculating mean and std
2023-08-07 21:24:56,827:INFO:Creating metrics dataframe
2023-08-07 21:24:56,968:INFO:Uploading results into container
2023-08-07 21:24:56,969:INFO:Uploading model into container now
2023-08-07 21:24:56,970:INFO:_master_model_container: 13
2023-08-07 21:24:56,970:INFO:_display_container: 2
2023-08-07 21:24:56,971:INFO:LGBMClassifier(boosting_type='gbdt', class_weight=None, colsample_bytree=1.0,
               importance_type='split', learning_rate=0.1, max_depth=-1,
               min_child_samples=20, min_child_weight=0.001, min_split_gain=0.0,
               n_estimators=100, n_jobs=-1, num_leaves=31, objective=None,
               random_state=123, reg_alpha=0.0, reg_lambda=0.0, subsample=1.0,
               subsample_for_bin=200000, subsample_freq=0)
2023-08-07 21:24:56,971:INFO:create_model() successfully completed......................................
2023-08-07 21:24:57,046:INFO:SubProcess create_model() end ==================================
2023-08-07 21:24:57,046:INFO:Creating metrics dataframe
2023-08-07 21:24:57,064:INFO:Initializing Dummy Classifier
2023-08-07 21:24:57,065:INFO:Total runtime is 1.0725760897000631 minutes
2023-08-07 21:24:57,069:INFO:SubProcess create_model() called ==================================
2023-08-07 21:24:57,070:INFO:Initializing create_model()
2023-08-07 21:24:57,071:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x0000026E1839CA30>, estimator=dummy, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x0000026E183EF340>, model_only=True, return_train_score=False, kwargs={})
2023-08-07 21:24:57,071:INFO:Checking exceptions
2023-08-07 21:24:57,071:INFO:Importing libraries
2023-08-07 21:24:57,071:INFO:Copying training dataset
2023-08-07 21:24:57,077:INFO:Defining folds
2023-08-07 21:24:57,077:INFO:Declaring metric variables
2023-08-07 21:24:57,083:INFO:Importing untrained model
2023-08-07 21:24:57,088:INFO:Dummy Classifier Imported successfully
2023-08-07 21:24:57,097:INFO:Starting cross validation
2023-08-07 21:24:57,100:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2023-08-07 21:24:57,429:WARNING:C:\Users\Sajjad Sindhi\AppData\Local\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

2023-08-07 21:24:57,438:WARNING:C:\Users\Sajjad Sindhi\AppData\Local\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

2023-08-07 21:24:57,452:WARNING:C:\Users\Sajjad Sindhi\AppData\Local\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

2023-08-07 21:24:57,461:WARNING:C:\Users\Sajjad Sindhi\AppData\Local\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

2023-08-07 21:24:57,466:WARNING:C:\Users\Sajjad Sindhi\AppData\Local\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

2023-08-07 21:24:57,502:WARNING:C:\Users\Sajjad Sindhi\AppData\Local\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

2023-08-07 21:24:57,507:WARNING:C:\Users\Sajjad Sindhi\AppData\Local\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

2023-08-07 21:24:57,521:WARNING:C:\Users\Sajjad Sindhi\AppData\Local\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

2023-08-07 21:24:58,064:WARNING:C:\Users\Sajjad Sindhi\AppData\Local\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

2023-08-07 21:24:58,122:WARNING:C:\Users\Sajjad Sindhi\AppData\Local\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

2023-08-07 21:24:59,630:INFO:Calculating mean and std
2023-08-07 21:24:59,634:INFO:Creating metrics dataframe
2023-08-07 21:24:59,983:INFO:Uploading results into container
2023-08-07 21:24:59,985:INFO:Uploading model into container now
2023-08-07 21:24:59,986:INFO:_master_model_container: 14
2023-08-07 21:24:59,987:INFO:_display_container: 2
2023-08-07 21:24:59,988:INFO:DummyClassifier(constant=None, random_state=123, strategy='prior')
2023-08-07 21:24:59,988:INFO:create_model() successfully completed......................................
2023-08-07 21:25:00,141:INFO:SubProcess create_model() end ==================================
2023-08-07 21:25:00,142:INFO:Creating metrics dataframe
2023-08-07 21:25:00,211:INFO:Initializing create_model()
2023-08-07 21:25:00,212:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x0000026E1839CA30>, estimator=LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=1000,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=123, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False), fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=False, predict=False, fit_kwargs={}, groups=None, refit=True, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=None, model_only=True, return_train_score=False, kwargs={})
2023-08-07 21:25:00,212:INFO:Checking exceptions
2023-08-07 21:25:00,217:INFO:Importing libraries
2023-08-07 21:25:00,217:INFO:Copying training dataset
2023-08-07 21:25:00,228:INFO:Defining folds
2023-08-07 21:25:00,228:INFO:Declaring metric variables
2023-08-07 21:25:00,229:INFO:Importing untrained model
2023-08-07 21:25:00,229:INFO:Declaring custom model
2023-08-07 21:25:00,231:INFO:Logistic Regression Imported successfully
2023-08-07 21:25:00,233:INFO:Cross validation set to False
2023-08-07 21:25:00,233:INFO:Fitting Model
2023-08-07 21:25:00,666:INFO:LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=1000,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=123, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)
2023-08-07 21:25:00,667:INFO:create_model() successfully completed......................................
2023-08-07 21:25:00,888:INFO:_master_model_container: 14
2023-08-07 21:25:00,889:INFO:_display_container: 2
2023-08-07 21:25:00,891:INFO:LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=1000,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=123, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)
2023-08-07 21:25:00,891:INFO:compare_models() successfully completed......................................
2023-08-07 21:25:00,892:INFO:Initializing compare_models()
2023-08-07 21:25:00,892:INFO:compare_models(self=<pycaret.classification.oop.ClassificationExperiment object at 0x0000026E22F07F70>, include=None, fold=None, round=4, cross_validation=True, sort=Accuracy, n_select=1, budget_time=None, turbo=True, errors=ignore, fit_kwargs=None, groups=None, experiment_custom_tags=None, probability_threshold=None, verbose=True, parallel=None, caller_params={'self': <pycaret.classification.oop.ClassificationExperiment object at 0x0000026E22F07F70>, 'include': None, 'exclude': None, 'fold': None, 'round': 4, 'cross_validation': True, 'sort': 'Accuracy', 'n_select': 1, 'budget_time': None, 'turbo': True, 'errors': 'ignore', 'fit_kwargs': None, 'groups': None, 'experiment_custom_tags': None, 'probability_threshold': None, 'engine': None, 'verbose': True, 'parallel': None, '__class__': <class 'pycaret.classification.oop.ClassificationExperiment'>}, exclude=None)
2023-08-07 21:25:00,893:INFO:Checking exceptions
2023-08-07 21:25:00,901:INFO:Preparing display monitor
2023-08-07 21:25:00,990:INFO:Initializing Logistic Regression
2023-08-07 21:25:00,991:INFO:Total runtime is 1.2862682342529298e-05 minutes
2023-08-07 21:25:01,002:INFO:SubProcess create_model() called ==================================
2023-08-07 21:25:01,003:INFO:Initializing create_model()
2023-08-07 21:25:01,003:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x0000026E22F07F70>, estimator=lr, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x0000026E1ED400D0>, model_only=True, return_train_score=False, kwargs={})
2023-08-07 21:25:01,003:INFO:Checking exceptions
2023-08-07 21:25:01,004:INFO:Importing libraries
2023-08-07 21:25:01,004:INFO:Copying training dataset
2023-08-07 21:25:01,015:INFO:Defining folds
2023-08-07 21:25:01,016:INFO:Declaring metric variables
2023-08-07 21:25:01,027:INFO:Importing untrained model
2023-08-07 21:25:01,042:INFO:Logistic Regression Imported successfully
2023-08-07 21:25:01,071:INFO:Starting cross validation
2023-08-07 21:25:01,075:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2023-08-07 21:25:03,679:INFO:Calculating mean and std
2023-08-07 21:25:03,682:INFO:Creating metrics dataframe
2023-08-07 21:25:04,037:INFO:Uploading results into container
2023-08-07 21:25:04,039:INFO:Uploading model into container now
2023-08-07 21:25:04,041:INFO:_master_model_container: 1
2023-08-07 21:25:04,041:INFO:_display_container: 2
2023-08-07 21:25:04,043:INFO:LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=1000,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=123, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)
2023-08-07 21:25:04,043:INFO:create_model() successfully completed......................................
2023-08-07 21:25:04,173:INFO:SubProcess create_model() end ==================================
2023-08-07 21:25:04,173:INFO:Creating metrics dataframe
2023-08-07 21:25:04,198:INFO:Initializing K Neighbors Classifier
2023-08-07 21:25:04,198:INFO:Total runtime is 0.053462811311086024 minutes
2023-08-07 21:25:04,210:INFO:SubProcess create_model() called ==================================
2023-08-07 21:25:04,211:INFO:Initializing create_model()
2023-08-07 21:25:04,212:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x0000026E22F07F70>, estimator=knn, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x0000026E1ED400D0>, model_only=True, return_train_score=False, kwargs={})
2023-08-07 21:25:04,213:INFO:Checking exceptions
2023-08-07 21:25:04,213:INFO:Importing libraries
2023-08-07 21:25:04,213:INFO:Copying training dataset
2023-08-07 21:25:04,225:INFO:Defining folds
2023-08-07 21:25:04,225:INFO:Declaring metric variables
2023-08-07 21:25:04,238:INFO:Importing untrained model
2023-08-07 21:25:04,248:INFO:K Neighbors Classifier Imported successfully
2023-08-07 21:25:04,280:INFO:Starting cross validation
2023-08-07 21:25:04,283:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2023-08-07 21:25:06,934:INFO:Calculating mean and std
2023-08-07 21:25:06,937:INFO:Creating metrics dataframe
2023-08-07 21:25:07,294:INFO:Uploading results into container
2023-08-07 21:25:07,296:INFO:Uploading model into container now
2023-08-07 21:25:07,298:INFO:_master_model_container: 2
2023-08-07 21:25:07,298:INFO:_display_container: 2
2023-08-07 21:25:07,300:INFO:KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=-1, n_neighbors=5, p=2,
                     weights='uniform')
2023-08-07 21:25:07,300:INFO:create_model() successfully completed......................................
2023-08-07 21:25:07,436:INFO:SubProcess create_model() end ==================================
2023-08-07 21:25:07,437:INFO:Creating metrics dataframe
2023-08-07 21:25:07,464:INFO:Initializing Naive Bayes
2023-08-07 21:25:07,465:INFO:Total runtime is 0.10791364113489788 minutes
2023-08-07 21:25:07,476:INFO:SubProcess create_model() called ==================================
2023-08-07 21:25:07,477:INFO:Initializing create_model()
2023-08-07 21:25:07,479:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x0000026E22F07F70>, estimator=nb, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x0000026E1ED400D0>, model_only=True, return_train_score=False, kwargs={})
2023-08-07 21:25:07,479:INFO:Checking exceptions
2023-08-07 21:25:07,479:INFO:Importing libraries
2023-08-07 21:25:07,480:INFO:Copying training dataset
2023-08-07 21:25:07,496:INFO:Defining folds
2023-08-07 21:25:07,497:INFO:Declaring metric variables
2023-08-07 21:25:07,514:INFO:Importing untrained model
2023-08-07 21:25:07,528:INFO:Naive Bayes Imported successfully
2023-08-07 21:25:07,553:INFO:Starting cross validation
2023-08-07 21:25:07,556:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2023-08-07 21:25:10,143:INFO:Calculating mean and std
2023-08-07 21:25:10,147:INFO:Creating metrics dataframe
2023-08-07 21:25:10,503:INFO:Uploading results into container
2023-08-07 21:25:10,506:INFO:Uploading model into container now
2023-08-07 21:25:10,507:INFO:_master_model_container: 3
2023-08-07 21:25:10,508:INFO:_display_container: 2
2023-08-07 21:25:10,509:INFO:GaussianNB(priors=None, var_smoothing=1e-09)
2023-08-07 21:25:10,509:INFO:create_model() successfully completed......................................
2023-08-07 21:25:10,648:INFO:SubProcess create_model() end ==================================
2023-08-07 21:25:10,649:INFO:Creating metrics dataframe
2023-08-07 21:25:10,678:INFO:Initializing Decision Tree Classifier
2023-08-07 21:25:10,679:INFO:Total runtime is 0.16148035128911337 minutes
2023-08-07 21:25:10,691:INFO:SubProcess create_model() called ==================================
2023-08-07 21:25:10,692:INFO:Initializing create_model()
2023-08-07 21:25:10,693:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x0000026E22F07F70>, estimator=dt, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x0000026E1ED400D0>, model_only=True, return_train_score=False, kwargs={})
2023-08-07 21:25:10,693:INFO:Checking exceptions
2023-08-07 21:25:10,694:INFO:Importing libraries
2023-08-07 21:25:10,694:INFO:Copying training dataset
2023-08-07 21:25:10,709:INFO:Defining folds
2023-08-07 21:25:10,710:INFO:Declaring metric variables
2023-08-07 21:25:10,723:INFO:Importing untrained model
2023-08-07 21:25:10,733:INFO:Decision Tree Classifier Imported successfully
2023-08-07 21:25:10,755:INFO:Starting cross validation
2023-08-07 21:25:10,758:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2023-08-07 21:25:13,340:INFO:Calculating mean and std
2023-08-07 21:25:13,343:INFO:Creating metrics dataframe
2023-08-07 21:25:13,695:INFO:Uploading results into container
2023-08-07 21:25:13,697:INFO:Uploading model into container now
2023-08-07 21:25:13,699:INFO:_master_model_container: 4
2023-08-07 21:25:13,699:INFO:_display_container: 2
2023-08-07 21:25:13,701:INFO:DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
                       max_depth=None, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_samples_leaf=1,
                       min_samples_split=2, min_weight_fraction_leaf=0.0,
                       random_state=123, splitter='best')
2023-08-07 21:25:13,702:INFO:create_model() successfully completed......................................
2023-08-07 21:25:13,836:INFO:SubProcess create_model() end ==================================
2023-08-07 21:25:13,837:INFO:Creating metrics dataframe
2023-08-07 21:25:13,868:INFO:Initializing SVM - Linear Kernel
2023-08-07 21:25:13,869:INFO:Total runtime is 0.2146470824877421 minutes
2023-08-07 21:25:13,879:INFO:SubProcess create_model() called ==================================
2023-08-07 21:25:13,880:INFO:Initializing create_model()
2023-08-07 21:25:13,881:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x0000026E22F07F70>, estimator=svm, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x0000026E1ED400D0>, model_only=True, return_train_score=False, kwargs={})
2023-08-07 21:25:13,881:INFO:Checking exceptions
2023-08-07 21:25:13,882:INFO:Importing libraries
2023-08-07 21:25:13,882:INFO:Copying training dataset
2023-08-07 21:25:13,898:INFO:Defining folds
2023-08-07 21:25:13,899:INFO:Declaring metric variables
2023-08-07 21:25:13,909:INFO:Importing untrained model
2023-08-07 21:25:13,919:INFO:SVM - Linear Kernel Imported successfully
2023-08-07 21:25:13,941:INFO:Starting cross validation
2023-08-07 21:25:13,946:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2023-08-07 21:25:14,205:WARNING:C:\Users\Sajjad Sindhi\AppData\Local\anaconda3\lib\site-packages\pycaret\internal\metrics.py:138: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "C:\Users\Sajjad Sindhi\AppData\Local\anaconda3\lib\site-packages\sklearn\metrics\_scorer.py", line 76, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Sajjad Sindhi\AppData\Local\anaconda3\lib\site-packages\pycaret\internal\metrics.py", line 130, in _score
    return super()._score(
  File "C:\Users\Sajjad Sindhi\AppData\Local\anaconda3\lib\site-packages\sklearn\metrics\_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "C:\Users\Sajjad Sindhi\AppData\Local\anaconda3\lib\site-packages\sklearn\metrics\_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
  File "C:\Users\Sajjad Sindhi\AppData\Local\anaconda3\lib\site-packages\pycaret\internal\pipeline.py", line 121, in __getattr__
    return getattr(self._final_estimator, name)
  File "C:\Users\Sajjad Sindhi\AppData\Local\anaconda3\lib\site-packages\sklearn\utils\_available_if.py", line 32, in __get__
    if not self.check(obj):
  File "C:\Users\Sajjad Sindhi\AppData\Local\anaconda3\lib\site-packages\sklearn\linear_model\_stochastic_gradient.py", line 1236, in _check_proba
    raise AttributeError(
AttributeError: probability estimates are not available for loss='hinge'

  warnings.warn(

2023-08-07 21:25:14,227:WARNING:C:\Users\Sajjad Sindhi\AppData\Local\anaconda3\lib\site-packages\pycaret\internal\metrics.py:138: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "C:\Users\Sajjad Sindhi\AppData\Local\anaconda3\lib\site-packages\sklearn\metrics\_scorer.py", line 76, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Sajjad Sindhi\AppData\Local\anaconda3\lib\site-packages\pycaret\internal\metrics.py", line 130, in _score
    return super()._score(
  File "C:\Users\Sajjad Sindhi\AppData\Local\anaconda3\lib\site-packages\sklearn\metrics\_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "C:\Users\Sajjad Sindhi\AppData\Local\anaconda3\lib\site-packages\sklearn\metrics\_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
  File "C:\Users\Sajjad Sindhi\AppData\Local\anaconda3\lib\site-packages\pycaret\internal\pipeline.py", line 121, in __getattr__
    return getattr(self._final_estimator, name)
  File "C:\Users\Sajjad Sindhi\AppData\Local\anaconda3\lib\site-packages\sklearn\utils\_available_if.py", line 32, in __get__
    if not self.check(obj):
  File "C:\Users\Sajjad Sindhi\AppData\Local\anaconda3\lib\site-packages\sklearn\linear_model\_stochastic_gradient.py", line 1236, in _check_proba
    raise AttributeError(
AttributeError: probability estimates are not available for loss='hinge'

  warnings.warn(

2023-08-07 21:25:14,252:WARNING:C:\Users\Sajjad Sindhi\AppData\Local\anaconda3\lib\site-packages\pycaret\internal\metrics.py:138: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "C:\Users\Sajjad Sindhi\AppData\Local\anaconda3\lib\site-packages\sklearn\metrics\_scorer.py", line 76, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Sajjad Sindhi\AppData\Local\anaconda3\lib\site-packages\pycaret\internal\metrics.py", line 130, in _score
    return super()._score(
  File "C:\Users\Sajjad Sindhi\AppData\Local\anaconda3\lib\site-packages\sklearn\metrics\_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "C:\Users\Sajjad Sindhi\AppData\Local\anaconda3\lib\site-packages\sklearn\metrics\_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
  File "C:\Users\Sajjad Sindhi\AppData\Local\anaconda3\lib\site-packages\pycaret\internal\pipeline.py", line 121, in __getattr__
    return getattr(self._final_estimator, name)
  File "C:\Users\Sajjad Sindhi\AppData\Local\anaconda3\lib\site-packages\sklearn\utils\_available_if.py", line 32, in __get__
    if not self.check(obj):
  File "C:\Users\Sajjad Sindhi\AppData\Local\anaconda3\lib\site-packages\sklearn\linear_model\_stochastic_gradient.py", line 1236, in _check_proba
    raise AttributeError(
AttributeError: probability estimates are not available for loss='hinge'

  warnings.warn(

2023-08-07 21:25:14,271:WARNING:C:\Users\Sajjad Sindhi\AppData\Local\anaconda3\lib\site-packages\pycaret\internal\metrics.py:138: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "C:\Users\Sajjad Sindhi\AppData\Local\anaconda3\lib\site-packages\sklearn\metrics\_scorer.py", line 76, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Sajjad Sindhi\AppData\Local\anaconda3\lib\site-packages\pycaret\internal\metrics.py", line 130, in _score
    return super()._score(
  File "C:\Users\Sajjad Sindhi\AppData\Local\anaconda3\lib\site-packages\sklearn\metrics\_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "C:\Users\Sajjad Sindhi\AppData\Local\anaconda3\lib\site-packages\sklearn\metrics\_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
  File "C:\Users\Sajjad Sindhi\AppData\Local\anaconda3\lib\site-packages\pycaret\internal\pipeline.py", line 121, in __getattr__
    return getattr(self._final_estimator, name)
  File "C:\Users\Sajjad Sindhi\AppData\Local\anaconda3\lib\site-packages\sklearn\utils\_available_if.py", line 32, in __get__
    if not self.check(obj):
  File "C:\Users\Sajjad Sindhi\AppData\Local\anaconda3\lib\site-packages\sklearn\linear_model\_stochastic_gradient.py", line 1236, in _check_proba
    raise AttributeError(
AttributeError: probability estimates are not available for loss='hinge'

  warnings.warn(

2023-08-07 21:25:14,300:WARNING:C:\Users\Sajjad Sindhi\AppData\Local\anaconda3\lib\site-packages\pycaret\internal\metrics.py:138: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "C:\Users\Sajjad Sindhi\AppData\Local\anaconda3\lib\site-packages\sklearn\metrics\_scorer.py", line 76, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Sajjad Sindhi\AppData\Local\anaconda3\lib\site-packages\pycaret\internal\metrics.py", line 130, in _score
    return super()._score(
  File "C:\Users\Sajjad Sindhi\AppData\Local\anaconda3\lib\site-packages\sklearn\metrics\_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "C:\Users\Sajjad Sindhi\AppData\Local\anaconda3\lib\site-packages\sklearn\metrics\_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
  File "C:\Users\Sajjad Sindhi\AppData\Local\anaconda3\lib\site-packages\pycaret\internal\pipeline.py", line 121, in __getattr__
    return getattr(self._final_estimator, name)
  File "C:\Users\Sajjad Sindhi\AppData\Local\anaconda3\lib\site-packages\sklearn\utils\_available_if.py", line 32, in __get__
    if not self.check(obj):
  File "C:\Users\Sajjad Sindhi\AppData\Local\anaconda3\lib\site-packages\sklearn\linear_model\_stochastic_gradient.py", line 1236, in _check_proba
    raise AttributeError(
AttributeError: probability estimates are not available for loss='hinge'

  warnings.warn(

2023-08-07 21:25:14,302:WARNING:C:\Users\Sajjad Sindhi\AppData\Local\anaconda3\lib\site-packages\pycaret\internal\metrics.py:138: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "C:\Users\Sajjad Sindhi\AppData\Local\anaconda3\lib\site-packages\sklearn\metrics\_scorer.py", line 76, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Sajjad Sindhi\AppData\Local\anaconda3\lib\site-packages\pycaret\internal\metrics.py", line 130, in _score
    return super()._score(
  File "C:\Users\Sajjad Sindhi\AppData\Local\anaconda3\lib\site-packages\sklearn\metrics\_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "C:\Users\Sajjad Sindhi\AppData\Local\anaconda3\lib\site-packages\sklearn\metrics\_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
  File "C:\Users\Sajjad Sindhi\AppData\Local\anaconda3\lib\site-packages\pycaret\internal\pipeline.py", line 121, in __getattr__
    return getattr(self._final_estimator, name)
  File "C:\Users\Sajjad Sindhi\AppData\Local\anaconda3\lib\site-packages\sklearn\utils\_available_if.py", line 32, in __get__
    if not self.check(obj):
  File "C:\Users\Sajjad Sindhi\AppData\Local\anaconda3\lib\site-packages\sklearn\linear_model\_stochastic_gradient.py", line 1236, in _check_proba
    raise AttributeError(
AttributeError: probability estimates are not available for loss='hinge'

  warnings.warn(

2023-08-07 21:25:14,314:WARNING:C:\Users\Sajjad Sindhi\AppData\Local\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

2023-08-07 21:25:14,325:WARNING:C:\Users\Sajjad Sindhi\AppData\Local\anaconda3\lib\site-packages\pycaret\internal\metrics.py:138: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "C:\Users\Sajjad Sindhi\AppData\Local\anaconda3\lib\site-packages\sklearn\metrics\_scorer.py", line 76, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Sajjad Sindhi\AppData\Local\anaconda3\lib\site-packages\pycaret\internal\metrics.py", line 130, in _score
    return super()._score(
  File "C:\Users\Sajjad Sindhi\AppData\Local\anaconda3\lib\site-packages\sklearn\metrics\_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "C:\Users\Sajjad Sindhi\AppData\Local\anaconda3\lib\site-packages\sklearn\metrics\_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
  File "C:\Users\Sajjad Sindhi\AppData\Local\anaconda3\lib\site-packages\pycaret\internal\pipeline.py", line 121, in __getattr__
    return getattr(self._final_estimator, name)
  File "C:\Users\Sajjad Sindhi\AppData\Local\anaconda3\lib\site-packages\sklearn\utils\_available_if.py", line 32, in __get__
    if not self.check(obj):
  File "C:\Users\Sajjad Sindhi\AppData\Local\anaconda3\lib\site-packages\sklearn\linear_model\_stochastic_gradient.py", line 1236, in _check_proba
    raise AttributeError(
AttributeError: probability estimates are not available for loss='hinge'

  warnings.warn(

2023-08-07 21:25:14,329:WARNING:C:\Users\Sajjad Sindhi\AppData\Local\anaconda3\lib\site-packages\pycaret\internal\metrics.py:138: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "C:\Users\Sajjad Sindhi\AppData\Local\anaconda3\lib\site-packages\sklearn\metrics\_scorer.py", line 76, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Sajjad Sindhi\AppData\Local\anaconda3\lib\site-packages\pycaret\internal\metrics.py", line 130, in _score
    return super()._score(
  File "C:\Users\Sajjad Sindhi\AppData\Local\anaconda3\lib\site-packages\sklearn\metrics\_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "C:\Users\Sajjad Sindhi\AppData\Local\anaconda3\lib\site-packages\sklearn\metrics\_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
  File "C:\Users\Sajjad Sindhi\AppData\Local\anaconda3\lib\site-packages\pycaret\internal\pipeline.py", line 121, in __getattr__
    return getattr(self._final_estimator, name)
  File "C:\Users\Sajjad Sindhi\AppData\Local\anaconda3\lib\site-packages\sklearn\utils\_available_if.py", line 32, in __get__
    if not self.check(obj):
  File "C:\Users\Sajjad Sindhi\AppData\Local\anaconda3\lib\site-packages\sklearn\linear_model\_stochastic_gradient.py", line 1236, in _check_proba
    raise AttributeError(
AttributeError: probability estimates are not available for loss='hinge'

  warnings.warn(

2023-08-07 21:25:14,334:WARNING:C:\Users\Sajjad Sindhi\AppData\Local\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

2023-08-07 21:25:14,829:WARNING:C:\Users\Sajjad Sindhi\AppData\Local\anaconda3\lib\site-packages\pycaret\internal\metrics.py:138: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "C:\Users\Sajjad Sindhi\AppData\Local\anaconda3\lib\site-packages\sklearn\metrics\_scorer.py", line 76, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Sajjad Sindhi\AppData\Local\anaconda3\lib\site-packages\pycaret\internal\metrics.py", line 130, in _score
    return super()._score(
  File "C:\Users\Sajjad Sindhi\AppData\Local\anaconda3\lib\site-packages\sklearn\metrics\_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "C:\Users\Sajjad Sindhi\AppData\Local\anaconda3\lib\site-packages\sklearn\metrics\_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
  File "C:\Users\Sajjad Sindhi\AppData\Local\anaconda3\lib\site-packages\pycaret\internal\pipeline.py", line 121, in __getattr__
    return getattr(self._final_estimator, name)
  File "C:\Users\Sajjad Sindhi\AppData\Local\anaconda3\lib\site-packages\sklearn\utils\_available_if.py", line 32, in __get__
    if not self.check(obj):
  File "C:\Users\Sajjad Sindhi\AppData\Local\anaconda3\lib\site-packages\sklearn\linear_model\_stochastic_gradient.py", line 1236, in _check_proba
    raise AttributeError(
AttributeError: probability estimates are not available for loss='hinge'

  warnings.warn(

2023-08-07 21:25:14,830:WARNING:C:\Users\Sajjad Sindhi\AppData\Local\anaconda3\lib\site-packages\pycaret\internal\metrics.py:138: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "C:\Users\Sajjad Sindhi\AppData\Local\anaconda3\lib\site-packages\sklearn\metrics\_scorer.py", line 76, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Sajjad Sindhi\AppData\Local\anaconda3\lib\site-packages\pycaret\internal\metrics.py", line 130, in _score
    return super()._score(
  File "C:\Users\Sajjad Sindhi\AppData\Local\anaconda3\lib\site-packages\sklearn\metrics\_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "C:\Users\Sajjad Sindhi\AppData\Local\anaconda3\lib\site-packages\sklearn\metrics\_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
  File "C:\Users\Sajjad Sindhi\AppData\Local\anaconda3\lib\site-packages\pycaret\internal\pipeline.py", line 121, in __getattr__
    return getattr(self._final_estimator, name)
  File "C:\Users\Sajjad Sindhi\AppData\Local\anaconda3\lib\site-packages\sklearn\utils\_available_if.py", line 32, in __get__
    if not self.check(obj):
  File "C:\Users\Sajjad Sindhi\AppData\Local\anaconda3\lib\site-packages\sklearn\linear_model\_stochastic_gradient.py", line 1236, in _check_proba
    raise AttributeError(
AttributeError: probability estimates are not available for loss='hinge'

  warnings.warn(

2023-08-07 21:25:16,399:INFO:Calculating mean and std
2023-08-07 21:25:16,402:INFO:Creating metrics dataframe
2023-08-07 21:25:16,757:INFO:Uploading results into container
2023-08-07 21:25:16,759:INFO:Uploading model into container now
2023-08-07 21:25:16,761:INFO:_master_model_container: 5
2023-08-07 21:25:16,761:INFO:_display_container: 2
2023-08-07 21:25:16,764:INFO:SGDClassifier(alpha=0.0001, average=False, class_weight=None,
              early_stopping=False, epsilon=0.1, eta0=0.001, fit_intercept=True,
              l1_ratio=0.15, learning_rate='optimal', loss='hinge',
              max_iter=1000, n_iter_no_change=5, n_jobs=-1, penalty='l2',
              power_t=0.5, random_state=123, shuffle=True, tol=0.001,
              validation_fraction=0.1, verbose=0, warm_start=False)
2023-08-07 21:25:16,764:INFO:create_model() successfully completed......................................
2023-08-07 21:25:16,897:INFO:SubProcess create_model() end ==================================
2023-08-07 21:25:16,897:INFO:Creating metrics dataframe
2023-08-07 21:25:16,929:INFO:Initializing Ridge Classifier
2023-08-07 21:25:16,929:INFO:Total runtime is 0.26564704577128095 minutes
2023-08-07 21:25:16,942:INFO:SubProcess create_model() called ==================================
2023-08-07 21:25:16,943:INFO:Initializing create_model()
2023-08-07 21:25:16,943:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x0000026E22F07F70>, estimator=ridge, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x0000026E1ED400D0>, model_only=True, return_train_score=False, kwargs={})
2023-08-07 21:25:16,944:INFO:Checking exceptions
2023-08-07 21:25:16,944:INFO:Importing libraries
2023-08-07 21:25:16,944:INFO:Copying training dataset
2023-08-07 21:25:16,956:INFO:Defining folds
2023-08-07 21:25:16,957:INFO:Declaring metric variables
2023-08-07 21:25:16,970:INFO:Importing untrained model
2023-08-07 21:25:16,984:INFO:Ridge Classifier Imported successfully
2023-08-07 21:25:17,008:INFO:Starting cross validation
2023-08-07 21:25:17,014:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2023-08-07 21:25:17,276:WARNING:C:\Users\Sajjad Sindhi\AppData\Local\anaconda3\lib\site-packages\pycaret\internal\metrics.py:138: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "C:\Users\Sajjad Sindhi\AppData\Local\anaconda3\lib\site-packages\sklearn\metrics\_scorer.py", line 76, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Sajjad Sindhi\AppData\Local\anaconda3\lib\site-packages\pycaret\internal\metrics.py", line 130, in _score
    return super()._score(
  File "C:\Users\Sajjad Sindhi\AppData\Local\anaconda3\lib\site-packages\sklearn\metrics\_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "C:\Users\Sajjad Sindhi\AppData\Local\anaconda3\lib\site-packages\sklearn\metrics\_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
  File "C:\Users\Sajjad Sindhi\AppData\Local\anaconda3\lib\site-packages\pycaret\internal\pipeline.py", line 121, in __getattr__
    return getattr(self._final_estimator, name)
AttributeError: 'RidgeClassifier' object has no attribute 'predict_proba'

  warnings.warn(

2023-08-07 21:25:17,312:WARNING:C:\Users\Sajjad Sindhi\AppData\Local\anaconda3\lib\site-packages\pycaret\internal\metrics.py:138: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "C:\Users\Sajjad Sindhi\AppData\Local\anaconda3\lib\site-packages\sklearn\metrics\_scorer.py", line 76, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Sajjad Sindhi\AppData\Local\anaconda3\lib\site-packages\pycaret\internal\metrics.py", line 130, in _score
    return super()._score(
  File "C:\Users\Sajjad Sindhi\AppData\Local\anaconda3\lib\site-packages\sklearn\metrics\_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "C:\Users\Sajjad Sindhi\AppData\Local\anaconda3\lib\site-packages\sklearn\metrics\_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
  File "C:\Users\Sajjad Sindhi\AppData\Local\anaconda3\lib\site-packages\pycaret\internal\pipeline.py", line 121, in __getattr__
    return getattr(self._final_estimator, name)
AttributeError: 'RidgeClassifier' object has no attribute 'predict_proba'

  warnings.warn(

2023-08-07 21:25:17,329:WARNING:C:\Users\Sajjad Sindhi\AppData\Local\anaconda3\lib\site-packages\pycaret\internal\metrics.py:138: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "C:\Users\Sajjad Sindhi\AppData\Local\anaconda3\lib\site-packages\sklearn\metrics\_scorer.py", line 76, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Sajjad Sindhi\AppData\Local\anaconda3\lib\site-packages\pycaret\internal\metrics.py", line 130, in _score
    return super()._score(
  File "C:\Users\Sajjad Sindhi\AppData\Local\anaconda3\lib\site-packages\sklearn\metrics\_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "C:\Users\Sajjad Sindhi\AppData\Local\anaconda3\lib\site-packages\sklearn\metrics\_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
  File "C:\Users\Sajjad Sindhi\AppData\Local\anaconda3\lib\site-packages\pycaret\internal\pipeline.py", line 121, in __getattr__
    return getattr(self._final_estimator, name)
AttributeError: 'RidgeClassifier' object has no attribute 'predict_proba'

  warnings.warn(

2023-08-07 21:25:17,336:WARNING:C:\Users\Sajjad Sindhi\AppData\Local\anaconda3\lib\site-packages\pycaret\internal\metrics.py:138: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "C:\Users\Sajjad Sindhi\AppData\Local\anaconda3\lib\site-packages\sklearn\metrics\_scorer.py", line 76, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Sajjad Sindhi\AppData\Local\anaconda3\lib\site-packages\pycaret\internal\metrics.py", line 130, in _score
    return super()._score(
  File "C:\Users\Sajjad Sindhi\AppData\Local\anaconda3\lib\site-packages\sklearn\metrics\_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "C:\Users\Sajjad Sindhi\AppData\Local\anaconda3\lib\site-packages\sklearn\metrics\_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
  File "C:\Users\Sajjad Sindhi\AppData\Local\anaconda3\lib\site-packages\pycaret\internal\pipeline.py", line 121, in __getattr__
    return getattr(self._final_estimator, name)
AttributeError: 'RidgeClassifier' object has no attribute 'predict_proba'

  warnings.warn(

2023-08-07 21:25:17,361:WARNING:C:\Users\Sajjad Sindhi\AppData\Local\anaconda3\lib\site-packages\pycaret\internal\metrics.py:138: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "C:\Users\Sajjad Sindhi\AppData\Local\anaconda3\lib\site-packages\sklearn\metrics\_scorer.py", line 76, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Sajjad Sindhi\AppData\Local\anaconda3\lib\site-packages\pycaret\internal\metrics.py", line 130, in _score
    return super()._score(
  File "C:\Users\Sajjad Sindhi\AppData\Local\anaconda3\lib\site-packages\sklearn\metrics\_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "C:\Users\Sajjad Sindhi\AppData\Local\anaconda3\lib\site-packages\sklearn\metrics\_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
  File "C:\Users\Sajjad Sindhi\AppData\Local\anaconda3\lib\site-packages\pycaret\internal\pipeline.py", line 121, in __getattr__
    return getattr(self._final_estimator, name)
AttributeError: 'RidgeClassifier' object has no attribute 'predict_proba'

  warnings.warn(

2023-08-07 21:25:17,382:WARNING:C:\Users\Sajjad Sindhi\AppData\Local\anaconda3\lib\site-packages\pycaret\internal\metrics.py:138: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "C:\Users\Sajjad Sindhi\AppData\Local\anaconda3\lib\site-packages\sklearn\metrics\_scorer.py", line 76, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Sajjad Sindhi\AppData\Local\anaconda3\lib\site-packages\pycaret\internal\metrics.py", line 130, in _score
    return super()._score(
  File "C:\Users\Sajjad Sindhi\AppData\Local\anaconda3\lib\site-packages\sklearn\metrics\_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "C:\Users\Sajjad Sindhi\AppData\Local\anaconda3\lib\site-packages\sklearn\metrics\_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
  File "C:\Users\Sajjad Sindhi\AppData\Local\anaconda3\lib\site-packages\pycaret\internal\pipeline.py", line 121, in __getattr__
    return getattr(self._final_estimator, name)
AttributeError: 'RidgeClassifier' object has no attribute 'predict_proba'

  warnings.warn(

2023-08-07 21:25:17,405:WARNING:C:\Users\Sajjad Sindhi\AppData\Local\anaconda3\lib\site-packages\pycaret\internal\metrics.py:138: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "C:\Users\Sajjad Sindhi\AppData\Local\anaconda3\lib\site-packages\sklearn\metrics\_scorer.py", line 76, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Sajjad Sindhi\AppData\Local\anaconda3\lib\site-packages\pycaret\internal\metrics.py", line 130, in _score
    return super()._score(
  File "C:\Users\Sajjad Sindhi\AppData\Local\anaconda3\lib\site-packages\sklearn\metrics\_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "C:\Users\Sajjad Sindhi\AppData\Local\anaconda3\lib\site-packages\sklearn\metrics\_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
  File "C:\Users\Sajjad Sindhi\AppData\Local\anaconda3\lib\site-packages\pycaret\internal\pipeline.py", line 121, in __getattr__
    return getattr(self._final_estimator, name)
AttributeError: 'RidgeClassifier' object has no attribute 'predict_proba'

  warnings.warn(

2023-08-07 21:25:17,412:WARNING:C:\Users\Sajjad Sindhi\AppData\Local\anaconda3\lib\site-packages\pycaret\internal\metrics.py:138: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "C:\Users\Sajjad Sindhi\AppData\Local\anaconda3\lib\site-packages\sklearn\metrics\_scorer.py", line 76, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Sajjad Sindhi\AppData\Local\anaconda3\lib\site-packages\pycaret\internal\metrics.py", line 130, in _score
    return super()._score(
  File "C:\Users\Sajjad Sindhi\AppData\Local\anaconda3\lib\site-packages\sklearn\metrics\_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "C:\Users\Sajjad Sindhi\AppData\Local\anaconda3\lib\site-packages\sklearn\metrics\_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
  File "C:\Users\Sajjad Sindhi\AppData\Local\anaconda3\lib\site-packages\pycaret\internal\pipeline.py", line 121, in __getattr__
    return getattr(self._final_estimator, name)
AttributeError: 'RidgeClassifier' object has no attribute 'predict_proba'

  warnings.warn(

2023-08-07 21:25:17,888:WARNING:C:\Users\Sajjad Sindhi\AppData\Local\anaconda3\lib\site-packages\pycaret\internal\metrics.py:138: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "C:\Users\Sajjad Sindhi\AppData\Local\anaconda3\lib\site-packages\sklearn\metrics\_scorer.py", line 76, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Sajjad Sindhi\AppData\Local\anaconda3\lib\site-packages\pycaret\internal\metrics.py", line 130, in _score
    return super()._score(
  File "C:\Users\Sajjad Sindhi\AppData\Local\anaconda3\lib\site-packages\sklearn\metrics\_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "C:\Users\Sajjad Sindhi\AppData\Local\anaconda3\lib\site-packages\sklearn\metrics\_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
  File "C:\Users\Sajjad Sindhi\AppData\Local\anaconda3\lib\site-packages\pycaret\internal\pipeline.py", line 121, in __getattr__
    return getattr(self._final_estimator, name)
AttributeError: 'RidgeClassifier' object has no attribute 'predict_proba'

  warnings.warn(

2023-08-07 21:25:17,994:WARNING:C:\Users\Sajjad Sindhi\AppData\Local\anaconda3\lib\site-packages\pycaret\internal\metrics.py:138: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "C:\Users\Sajjad Sindhi\AppData\Local\anaconda3\lib\site-packages\sklearn\metrics\_scorer.py", line 76, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Sajjad Sindhi\AppData\Local\anaconda3\lib\site-packages\pycaret\internal\metrics.py", line 130, in _score
    return super()._score(
  File "C:\Users\Sajjad Sindhi\AppData\Local\anaconda3\lib\site-packages\sklearn\metrics\_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "C:\Users\Sajjad Sindhi\AppData\Local\anaconda3\lib\site-packages\sklearn\metrics\_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
  File "C:\Users\Sajjad Sindhi\AppData\Local\anaconda3\lib\site-packages\pycaret\internal\pipeline.py", line 121, in __getattr__
    return getattr(self._final_estimator, name)
AttributeError: 'RidgeClassifier' object has no attribute 'predict_proba'

  warnings.warn(

2023-08-07 21:25:19,520:INFO:Calculating mean and std
2023-08-07 21:25:19,524:INFO:Creating metrics dataframe
2023-08-07 21:25:19,877:INFO:Uploading results into container
2023-08-07 21:25:19,879:INFO:Uploading model into container now
2023-08-07 21:25:19,881:INFO:_master_model_container: 6
2023-08-07 21:25:19,881:INFO:_display_container: 2
2023-08-07 21:25:19,883:INFO:RidgeClassifier(alpha=1.0, class_weight=None, copy_X=True, fit_intercept=True,
                max_iter=None, positive=False, random_state=123, solver='auto',
                tol=0.0001)
2023-08-07 21:25:19,883:INFO:create_model() successfully completed......................................
2023-08-07 21:25:20,022:INFO:SubProcess create_model() end ==================================
2023-08-07 21:25:20,023:INFO:Creating metrics dataframe
2023-08-07 21:25:20,057:INFO:Initializing Random Forest Classifier
2023-08-07 21:25:20,058:INFO:Total runtime is 0.31779203414916996 minutes
2023-08-07 21:25:20,072:INFO:SubProcess create_model() called ==================================
2023-08-07 21:25:20,073:INFO:Initializing create_model()
2023-08-07 21:25:20,073:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x0000026E22F07F70>, estimator=rf, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x0000026E1ED400D0>, model_only=True, return_train_score=False, kwargs={})
2023-08-07 21:25:20,074:INFO:Checking exceptions
2023-08-07 21:25:20,074:INFO:Importing libraries
2023-08-07 21:25:20,074:INFO:Copying training dataset
2023-08-07 21:25:20,085:INFO:Defining folds
2023-08-07 21:25:20,086:INFO:Declaring metric variables
2023-08-07 21:25:20,097:INFO:Importing untrained model
2023-08-07 21:25:20,108:INFO:Random Forest Classifier Imported successfully
2023-08-07 21:25:20,129:INFO:Starting cross validation
2023-08-07 21:25:20,132:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2023-08-07 21:25:23,825:INFO:Calculating mean and std
2023-08-07 21:25:23,829:INFO:Creating metrics dataframe
2023-08-07 21:25:24,190:INFO:Uploading results into container
2023-08-07 21:25:24,192:INFO:Uploading model into container now
2023-08-07 21:25:24,194:INFO:_master_model_container: 7
2023-08-07 21:25:24,195:INFO:_display_container: 2
2023-08-07 21:25:24,196:INFO:RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='sqrt',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_samples_leaf=1,
                       min_samples_split=2, min_weight_fraction_leaf=0.0,
                       n_estimators=100, n_jobs=-1, oob_score=False,
                       random_state=123, verbose=0, warm_start=False)
2023-08-07 21:25:24,197:INFO:create_model() successfully completed......................................
2023-08-07 21:25:24,329:INFO:SubProcess create_model() end ==================================
2023-08-07 21:25:24,330:INFO:Creating metrics dataframe
2023-08-07 21:25:24,361:INFO:Initializing Quadratic Discriminant Analysis
2023-08-07 21:25:24,362:INFO:Total runtime is 0.3895244359970093 minutes
2023-08-07 21:25:24,374:INFO:SubProcess create_model() called ==================================
2023-08-07 21:25:24,375:INFO:Initializing create_model()
2023-08-07 21:25:24,376:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x0000026E22F07F70>, estimator=qda, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x0000026E1ED400D0>, model_only=True, return_train_score=False, kwargs={})
2023-08-07 21:25:24,376:INFO:Checking exceptions
2023-08-07 21:25:24,376:INFO:Importing libraries
2023-08-07 21:25:24,377:INFO:Copying training dataset
2023-08-07 21:25:24,388:INFO:Defining folds
2023-08-07 21:25:24,389:INFO:Declaring metric variables
2023-08-07 21:25:24,402:INFO:Importing untrained model
2023-08-07 21:25:24,415:INFO:Quadratic Discriminant Analysis Imported successfully
2023-08-07 21:25:24,438:INFO:Starting cross validation
2023-08-07 21:25:24,441:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2023-08-07 21:25:27,004:INFO:Calculating mean and std
2023-08-07 21:25:27,007:INFO:Creating metrics dataframe
2023-08-07 21:25:27,373:INFO:Uploading results into container
2023-08-07 21:25:27,375:INFO:Uploading model into container now
2023-08-07 21:25:27,376:INFO:_master_model_container: 8
2023-08-07 21:25:27,377:INFO:_display_container: 2
2023-08-07 21:25:27,378:INFO:QuadraticDiscriminantAnalysis(priors=None, reg_param=0.0,
                              store_covariance=False, tol=0.0001)
2023-08-07 21:25:27,378:INFO:create_model() successfully completed......................................
2023-08-07 21:25:27,511:INFO:SubProcess create_model() end ==================================
2023-08-07 21:25:27,512:INFO:Creating metrics dataframe
2023-08-07 21:25:27,544:INFO:Initializing Ada Boost Classifier
2023-08-07 21:25:27,544:INFO:Total runtime is 0.4425588329633077 minutes
2023-08-07 21:25:27,556:INFO:SubProcess create_model() called ==================================
2023-08-07 21:25:27,557:INFO:Initializing create_model()
2023-08-07 21:25:27,558:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x0000026E22F07F70>, estimator=ada, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x0000026E1ED400D0>, model_only=True, return_train_score=False, kwargs={})
2023-08-07 21:25:27,558:INFO:Checking exceptions
2023-08-07 21:25:27,559:INFO:Importing libraries
2023-08-07 21:25:27,559:INFO:Copying training dataset
2023-08-07 21:25:27,577:INFO:Defining folds
2023-08-07 21:25:27,577:INFO:Declaring metric variables
2023-08-07 21:25:27,589:INFO:Importing untrained model
2023-08-07 21:25:27,599:INFO:Ada Boost Classifier Imported successfully
2023-08-07 21:25:27,623:INFO:Starting cross validation
2023-08-07 21:25:27,626:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2023-08-07 21:25:30,690:INFO:Calculating mean and std
2023-08-07 21:25:30,694:INFO:Creating metrics dataframe
2023-08-07 21:25:31,044:INFO:Uploading results into container
2023-08-07 21:25:31,046:INFO:Uploading model into container now
2023-08-07 21:25:31,048:INFO:_master_model_container: 9
2023-08-07 21:25:31,048:INFO:_display_container: 2
2023-08-07 21:25:31,050:INFO:AdaBoostClassifier(algorithm='SAMME.R', base_estimator='deprecated',
                   estimator=None, learning_rate=1.0, n_estimators=50,
                   random_state=123)
2023-08-07 21:25:31,050:INFO:create_model() successfully completed......................................
2023-08-07 21:25:31,187:INFO:SubProcess create_model() end ==================================
2023-08-07 21:25:31,188:INFO:Creating metrics dataframe
2023-08-07 21:25:31,221:INFO:Initializing Gradient Boosting Classifier
2023-08-07 21:25:31,222:INFO:Total runtime is 0.5038588205973308 minutes
2023-08-07 21:25:31,233:INFO:SubProcess create_model() called ==================================
2023-08-07 21:25:31,234:INFO:Initializing create_model()
2023-08-07 21:25:31,235:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x0000026E22F07F70>, estimator=gbc, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x0000026E1ED400D0>, model_only=True, return_train_score=False, kwargs={})
2023-08-07 21:25:31,235:INFO:Checking exceptions
2023-08-07 21:25:31,235:INFO:Importing libraries
2023-08-07 21:25:31,236:INFO:Copying training dataset
2023-08-07 21:25:31,253:INFO:Defining folds
2023-08-07 21:25:31,253:INFO:Declaring metric variables
2023-08-07 21:25:31,261:INFO:Importing untrained model
2023-08-07 21:25:31,271:INFO:Gradient Boosting Classifier Imported successfully
2023-08-07 21:25:31,295:INFO:Starting cross validation
2023-08-07 21:25:31,298:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2023-08-07 21:25:34,365:INFO:Calculating mean and std
2023-08-07 21:25:34,368:INFO:Creating metrics dataframe
2023-08-07 21:25:34,731:INFO:Uploading results into container
2023-08-07 21:25:34,733:INFO:Uploading model into container now
2023-08-07 21:25:34,734:INFO:_master_model_container: 10
2023-08-07 21:25:34,735:INFO:_display_container: 2
2023-08-07 21:25:34,737:INFO:GradientBoostingClassifier(ccp_alpha=0.0, criterion='friedman_mse', init=None,
                           learning_rate=0.1, loss='log_loss', max_depth=3,
                           max_features=None, max_leaf_nodes=None,
                           min_impurity_decrease=0.0, min_samples_leaf=1,
                           min_samples_split=2, min_weight_fraction_leaf=0.0,
                           n_estimators=100, n_iter_no_change=None,
                           random_state=123, subsample=1.0, tol=0.0001,
                           validation_fraction=0.1, verbose=0,
                           warm_start=False)
2023-08-07 21:25:34,738:INFO:create_model() successfully completed......................................
2023-08-07 21:25:34,874:INFO:SubProcess create_model() end ==================================
2023-08-07 21:25:34,875:INFO:Creating metrics dataframe
2023-08-07 21:25:34,908:INFO:Initializing Linear Discriminant Analysis
2023-08-07 21:25:34,909:INFO:Total runtime is 0.5653088251749675 minutes
2023-08-07 21:25:34,922:INFO:SubProcess create_model() called ==================================
2023-08-07 21:25:34,923:INFO:Initializing create_model()
2023-08-07 21:25:34,924:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x0000026E22F07F70>, estimator=lda, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x0000026E1ED400D0>, model_only=True, return_train_score=False, kwargs={})
2023-08-07 21:25:34,924:INFO:Checking exceptions
2023-08-07 21:25:34,924:INFO:Importing libraries
2023-08-07 21:25:34,924:INFO:Copying training dataset
2023-08-07 21:25:34,936:INFO:Defining folds
2023-08-07 21:25:34,937:INFO:Declaring metric variables
2023-08-07 21:25:34,949:INFO:Importing untrained model
2023-08-07 21:25:34,963:INFO:Linear Discriminant Analysis Imported successfully
2023-08-07 21:25:34,984:INFO:Starting cross validation
2023-08-07 21:25:34,987:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2023-08-07 21:25:37,609:INFO:Calculating mean and std
2023-08-07 21:25:37,612:INFO:Creating metrics dataframe
2023-08-07 21:25:37,969:INFO:Uploading results into container
2023-08-07 21:25:37,971:INFO:Uploading model into container now
2023-08-07 21:25:37,973:INFO:_master_model_container: 11
2023-08-07 21:25:37,973:INFO:_display_container: 2
2023-08-07 21:25:37,974:INFO:LinearDiscriminantAnalysis(covariance_estimator=None, n_components=None,
                           priors=None, shrinkage=None, solver='svd',
                           store_covariance=False, tol=0.0001)
2023-08-07 21:25:37,975:INFO:create_model() successfully completed......................................
2023-08-07 21:25:38,112:INFO:SubProcess create_model() end ==================================
2023-08-07 21:25:38,113:INFO:Creating metrics dataframe
2023-08-07 21:25:38,146:INFO:Initializing Extra Trees Classifier
2023-08-07 21:25:38,147:INFO:Total runtime is 0.6192752917607626 minutes
2023-08-07 21:25:38,158:INFO:SubProcess create_model() called ==================================
2023-08-07 21:25:38,159:INFO:Initializing create_model()
2023-08-07 21:25:38,161:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x0000026E22F07F70>, estimator=et, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x0000026E1ED400D0>, model_only=True, return_train_score=False, kwargs={})
2023-08-07 21:25:38,161:INFO:Checking exceptions
2023-08-07 21:25:38,161:INFO:Importing libraries
2023-08-07 21:25:38,162:INFO:Copying training dataset
2023-08-07 21:25:38,173:INFO:Defining folds
2023-08-07 21:25:38,174:INFO:Declaring metric variables
2023-08-07 21:25:38,185:INFO:Importing untrained model
2023-08-07 21:25:38,196:INFO:Extra Trees Classifier Imported successfully
2023-08-07 21:25:38,221:INFO:Starting cross validation
2023-08-07 21:25:38,224:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2023-08-07 21:25:41,904:INFO:Calculating mean and std
2023-08-07 21:25:41,909:INFO:Creating metrics dataframe
2023-08-07 21:25:42,188:INFO:Uploading results into container
2023-08-07 21:25:42,191:INFO:Uploading model into container now
2023-08-07 21:25:42,192:INFO:_master_model_container: 12
2023-08-07 21:25:42,193:INFO:_display_container: 2
2023-08-07 21:25:42,195:INFO:ExtraTreesClassifier(bootstrap=False, ccp_alpha=0.0, class_weight=None,
                     criterion='gini', max_depth=None, max_features='sqrt',
                     max_leaf_nodes=None, max_samples=None,
                     min_impurity_decrease=0.0, min_samples_leaf=1,
                     min_samples_split=2, min_weight_fraction_leaf=0.0,
                     n_estimators=100, n_jobs=-1, oob_score=False,
                     random_state=123, verbose=0, warm_start=False)
2023-08-07 21:25:42,195:INFO:create_model() successfully completed......................................
2023-08-07 21:25:42,331:INFO:SubProcess create_model() end ==================================
2023-08-07 21:25:42,333:INFO:Creating metrics dataframe
2023-08-07 21:25:42,389:INFO:Initializing Light Gradient Boosting Machine
2023-08-07 21:25:42,389:INFO:Total runtime is 0.6899791399637858 minutes
2023-08-07 21:25:42,397:INFO:SubProcess create_model() called ==================================
2023-08-07 21:25:42,398:INFO:Initializing create_model()
2023-08-07 21:25:42,398:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x0000026E22F07F70>, estimator=lightgbm, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x0000026E1ED400D0>, model_only=True, return_train_score=False, kwargs={})
2023-08-07 21:25:42,399:INFO:Checking exceptions
2023-08-07 21:25:42,399:INFO:Importing libraries
2023-08-07 21:25:42,399:INFO:Copying training dataset
2023-08-07 21:25:42,409:INFO:Defining folds
2023-08-07 21:25:42,410:INFO:Declaring metric variables
2023-08-07 21:25:42,421:INFO:Importing untrained model
2023-08-07 21:25:42,433:INFO:Light Gradient Boosting Machine Imported successfully
2023-08-07 21:25:42,454:INFO:Starting cross validation
2023-08-07 21:25:42,457:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2023-08-07 21:25:42,643:WARNING:C:\Users\Sajjad Sindhi\AppData\Local\anaconda3\lib\site-packages\sklearn\base.py:299: UserWarning: Trying to unpickle estimator LabelEncoder from version 1.2.2 when using version 1.2.1. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/model_persistence.html#security-maintainability-limitations
  warnings.warn(

2023-08-07 21:25:42,655:WARNING:C:\Users\Sajjad Sindhi\AppData\Local\anaconda3\lib\site-packages\sklearn\base.py:299: UserWarning: Trying to unpickle estimator LabelEncoder from version 1.2.2 when using version 1.2.1. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/model_persistence.html#security-maintainability-limitations
  warnings.warn(

2023-08-07 21:25:42,684:WARNING:C:\Users\Sajjad Sindhi\AppData\Local\anaconda3\lib\site-packages\sklearn\base.py:299: UserWarning: Trying to unpickle estimator LabelEncoder from version 1.2.2 when using version 1.2.1. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/model_persistence.html#security-maintainability-limitations
  warnings.warn(

2023-08-07 21:25:42,690:WARNING:C:\Users\Sajjad Sindhi\AppData\Local\anaconda3\lib\site-packages\sklearn\base.py:299: UserWarning: Trying to unpickle estimator LabelEncoder from version 1.2.2 when using version 1.2.1. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/model_persistence.html#security-maintainability-limitations
  warnings.warn(

2023-08-07 21:25:42,736:WARNING:C:\Users\Sajjad Sindhi\AppData\Local\anaconda3\lib\site-packages\sklearn\base.py:299: UserWarning: Trying to unpickle estimator LabelEncoder from version 1.2.2 when using version 1.2.1. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/model_persistence.html#security-maintainability-limitations
  warnings.warn(

2023-08-07 21:25:42,744:WARNING:C:\Users\Sajjad Sindhi\AppData\Local\anaconda3\lib\site-packages\sklearn\base.py:299: UserWarning: Trying to unpickle estimator LabelEncoder from version 1.2.2 when using version 1.2.1. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/model_persistence.html#security-maintainability-limitations
  warnings.warn(

2023-08-07 21:25:42,745:WARNING:C:\Users\Sajjad Sindhi\AppData\Local\anaconda3\lib\site-packages\sklearn\base.py:299: UserWarning: Trying to unpickle estimator LabelEncoder from version 1.2.2 when using version 1.2.1. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/model_persistence.html#security-maintainability-limitations
  warnings.warn(

2023-08-07 21:25:42,762:WARNING:C:\Users\Sajjad Sindhi\AppData\Local\anaconda3\lib\site-packages\sklearn\base.py:299: UserWarning: Trying to unpickle estimator LabelEncoder from version 1.2.2 when using version 1.2.1. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/model_persistence.html#security-maintainability-limitations
  warnings.warn(

2023-08-07 21:25:43,533:WARNING:C:\Users\Sajjad Sindhi\AppData\Local\anaconda3\lib\site-packages\sklearn\base.py:299: UserWarning: Trying to unpickle estimator LabelEncoder from version 1.2.2 when using version 1.2.1. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/model_persistence.html#security-maintainability-limitations
  warnings.warn(

2023-08-07 21:25:43,579:WARNING:C:\Users\Sajjad Sindhi\AppData\Local\anaconda3\lib\site-packages\sklearn\base.py:299: UserWarning: Trying to unpickle estimator LabelEncoder from version 1.2.2 when using version 1.2.1. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/model_persistence.html#security-maintainability-limitations
  warnings.warn(

2023-08-07 21:25:45,119:INFO:Calculating mean and std
2023-08-07 21:25:45,124:INFO:Creating metrics dataframe
2023-08-07 21:25:45,471:INFO:Uploading results into container
2023-08-07 21:25:45,474:INFO:Uploading model into container now
2023-08-07 21:25:45,475:INFO:_master_model_container: 13
2023-08-07 21:25:45,475:INFO:_display_container: 2
2023-08-07 21:25:45,477:INFO:LGBMClassifier(boosting_type='gbdt', class_weight=None, colsample_bytree=1.0,
               importance_type='split', learning_rate=0.1, max_depth=-1,
               min_child_samples=20, min_child_weight=0.001, min_split_gain=0.0,
               n_estimators=100, n_jobs=-1, num_leaves=31, objective=None,
               random_state=123, reg_alpha=0.0, reg_lambda=0.0, subsample=1.0,
               subsample_for_bin=200000, subsample_freq=0)
2023-08-07 21:25:45,477:INFO:create_model() successfully completed......................................
2023-08-07 21:25:45,641:INFO:SubProcess create_model() end ==================================
2023-08-07 21:25:45,642:INFO:Creating metrics dataframe
2023-08-07 21:25:45,696:INFO:Initializing Dummy Classifier
2023-08-07 21:25:45,697:INFO:Total runtime is 0.7451127012570699 minutes
2023-08-07 21:25:45,711:INFO:SubProcess create_model() called ==================================
2023-08-07 21:25:45,712:INFO:Initializing create_model()
2023-08-07 21:25:45,712:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x0000026E22F07F70>, estimator=dummy, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x0000026E1ED400D0>, model_only=True, return_train_score=False, kwargs={})
2023-08-07 21:25:45,713:INFO:Checking exceptions
2023-08-07 21:25:45,713:INFO:Importing libraries
2023-08-07 21:25:45,713:INFO:Copying training dataset
2023-08-07 21:25:45,721:INFO:Defining folds
2023-08-07 21:25:45,721:INFO:Declaring metric variables
2023-08-07 21:25:45,726:INFO:Importing untrained model
2023-08-07 21:25:45,733:INFO:Dummy Classifier Imported successfully
2023-08-07 21:25:45,748:INFO:Starting cross validation
2023-08-07 21:25:45,751:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2023-08-07 21:25:46,054:WARNING:C:\Users\Sajjad Sindhi\AppData\Local\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

2023-08-07 21:25:46,075:WARNING:C:\Users\Sajjad Sindhi\AppData\Local\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

2023-08-07 21:25:46,086:WARNING:C:\Users\Sajjad Sindhi\AppData\Local\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

2023-08-07 21:25:46,087:WARNING:C:\Users\Sajjad Sindhi\AppData\Local\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

2023-08-07 21:25:46,111:WARNING:C:\Users\Sajjad Sindhi\AppData\Local\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

2023-08-07 21:25:46,143:WARNING:C:\Users\Sajjad Sindhi\AppData\Local\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

2023-08-07 21:25:46,147:WARNING:C:\Users\Sajjad Sindhi\AppData\Local\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

2023-08-07 21:25:46,149:WARNING:C:\Users\Sajjad Sindhi\AppData\Local\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

2023-08-07 21:25:46,787:WARNING:C:\Users\Sajjad Sindhi\AppData\Local\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

2023-08-07 21:25:46,799:WARNING:C:\Users\Sajjad Sindhi\AppData\Local\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

2023-08-07 21:25:48,314:INFO:Calculating mean and std
2023-08-07 21:25:48,318:INFO:Creating metrics dataframe
2023-08-07 21:25:48,679:INFO:Uploading results into container
2023-08-07 21:25:48,681:INFO:Uploading model into container now
2023-08-07 21:25:48,682:INFO:_master_model_container: 14
2023-08-07 21:25:48,683:INFO:_display_container: 2
2023-08-07 21:25:48,684:INFO:DummyClassifier(constant=None, random_state=123, strategy='prior')
2023-08-07 21:25:48,684:INFO:create_model() successfully completed......................................
2023-08-07 21:25:48,819:INFO:SubProcess create_model() end ==================================
2023-08-07 21:25:48,820:INFO:Creating metrics dataframe
2023-08-07 21:25:48,889:INFO:Initializing create_model()
2023-08-07 21:25:48,890:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x0000026E22F07F70>, estimator=LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=1000,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=123, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False), fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=False, predict=False, fit_kwargs={}, groups=None, refit=True, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=None, model_only=True, return_train_score=False, kwargs={})
2023-08-07 21:25:48,890:INFO:Checking exceptions
2023-08-07 21:25:48,894:INFO:Importing libraries
2023-08-07 21:25:48,894:INFO:Copying training dataset
2023-08-07 21:25:48,901:INFO:Defining folds
2023-08-07 21:25:48,901:INFO:Declaring metric variables
2023-08-07 21:25:48,901:INFO:Importing untrained model
2023-08-07 21:25:48,901:INFO:Declaring custom model
2023-08-07 21:25:48,903:INFO:Logistic Regression Imported successfully
2023-08-07 21:25:48,904:INFO:Cross validation set to False
2023-08-07 21:25:48,905:INFO:Fitting Model
2023-08-07 21:25:49,308:INFO:LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=1000,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=123, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)
2023-08-07 21:25:49,309:INFO:create_model() successfully completed......................................
2023-08-07 21:25:49,535:INFO:_master_model_container: 14
2023-08-07 21:25:49,536:INFO:_display_container: 2
2023-08-07 21:25:49,538:INFO:LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=1000,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=123, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)
2023-08-07 21:25:49,538:INFO:compare_models() successfully completed......................................
2023-08-07 21:26:00,111:INFO:Initializing predict_model()
2023-08-07 21:26:00,111:INFO:predict_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x0000026E1839CA30>, estimator=LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=1000,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=123, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False), probability_threshold=None, encoded_labels=False, raw_score=False, round=4, verbose=True, ml_usecase=None, preprocess=True, encode_labels=<function _SupervisedExperiment.predict_model.<locals>.encode_labels at 0x0000026E22C175B0>)
2023-08-07 21:26:00,112:INFO:Checking exceptions
2023-08-07 21:26:00,112:INFO:Preloading libraries
2023-08-07 21:26:00,118:INFO:Set up data.
2023-08-07 21:26:00,134:INFO:Set up index.
2023-08-07 21:26:00,355:INFO:Initializing predict_model()
2023-08-07 21:26:00,355:INFO:predict_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x0000026E22F07F70>, estimator=LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=1000,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=123, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False), probability_threshold=None, encoded_labels=False, raw_score=False, round=4, verbose=True, ml_usecase=None, preprocess=True, encode_labels=<function _SupervisedExperiment.predict_model.<locals>.encode_labels at 0x0000026E18839F30>)
2023-08-07 21:26:00,355:INFO:Checking exceptions
2023-08-07 21:26:00,356:INFO:Preloading libraries
2023-08-07 21:26:00,360:INFO:Set up data.
2023-08-07 21:26:00,374:INFO:Set up index.
2023-08-07 21:26:10,522:INFO:Initializing predict_model()
2023-08-07 21:26:10,523:INFO:predict_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x0000026E1839CA30>, estimator=LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=1000,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=123, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False), probability_threshold=None, encoded_labels=False, raw_score=True, round=4, verbose=True, ml_usecase=None, preprocess=True, encode_labels=<function _SupervisedExperiment.predict_model.<locals>.encode_labels at 0x0000026E22C15750>)
2023-08-07 21:26:10,523:INFO:Checking exceptions
2023-08-07 21:26:10,524:INFO:Preloading libraries
2023-08-07 21:26:10,528:INFO:Set up data.
2023-08-07 21:26:10,548:INFO:Set up index.
2023-08-07 21:26:10,787:INFO:Initializing predict_model()
2023-08-07 21:26:10,787:INFO:predict_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x0000026E22F07F70>, estimator=LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=1000,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=123, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False), probability_threshold=None, encoded_labels=False, raw_score=True, round=4, verbose=True, ml_usecase=None, preprocess=True, encode_labels=<function _SupervisedExperiment.predict_model.<locals>.encode_labels at 0x0000026E22C15750>)
2023-08-07 21:26:10,788:INFO:Checking exceptions
2023-08-07 21:26:10,788:INFO:Preloading libraries
2023-08-07 21:26:10,793:INFO:Set up data.
2023-08-07 21:26:10,807:INFO:Set up index.
2023-08-07 21:26:24,060:INFO:Initializing save_model()
2023-08-07 21:26:24,061:INFO:save_model(model=LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=1000,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=123, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False), model_name=my_best_pipeline, prep_pipe_=Pipeline(memory=FastMemory(location=C:\Users\SAJJAD~1\AppData\Local\Temp\joblib),
         steps=[('numerical_imputer',
                 TransformerWrapper(exclude=None,
                                    include=['Number of times pregnant',
                                             'Plasma glucose concentration a 2 '
                                             'hours in an oral glucose '
                                             'tolerance test',
                                             'Diastolic blood pressure (mm Hg)',
                                             'Triceps skin fold thickness (mm)',
                                             '2-Hour serum insulin (mu U/ml)',
                                             'Body mass index (we...
                 TransformerWrapper(exclude=None, include=[],
                                    transformer=SimpleImputer(add_indicator=False,
                                                              copy=True,
                                                              fill_value=None,
                                                              keep_empty_features=False,
                                                              missing_values=nan,
                                                              strategy='most_frequent',
                                                              verbose='deprecated'))),
                ('clean_column_names',
                 TransformerWrapper(exclude=None, include=None,
                                    transformer=CleanColumnNames(match='[\\]\\[\\,\\{\\}\\"\\:]+')))],
         verbose=False), verbose=True, use_case=MLUsecase.CLASSIFICATION, kwargs={})
2023-08-07 21:26:24,061:INFO:Adding model into prep_pipe
2023-08-07 21:26:24,081:INFO:my_best_pipeline.pkl saved in current working directory
2023-08-07 21:26:24,101:INFO:Pipeline(memory=FastMemory(location=C:\Users\SAJJAD~1\AppData\Local\Temp\joblib),
         steps=[('numerical_imputer',
                 TransformerWrapper(exclude=None,
                                    include=['Number of times pregnant',
                                             'Plasma glucose concentration a 2 '
                                             'hours in an oral glucose '
                                             'tolerance test',
                                             'Diastolic blood pressure (mm Hg)',
                                             'Triceps skin fold thickness (mm)',
                                             '2-Hour serum insulin (mu U/ml)',
                                             'Body mass index (we...
                 TransformerWrapper(exclude=None, include=None,
                                    transformer=CleanColumnNames(match='[\\]\\[\\,\\{\\}\\"\\:]+'))),
                ('trained_model',
                 LogisticRegression(C=1.0, class_weight=None, dual=False,
                                    fit_intercept=True, intercept_scaling=1,
                                    l1_ratio=None, max_iter=1000,
                                    multi_class='auto', n_jobs=None,
                                    penalty='l2', random_state=123,
                                    solver='lbfgs', tol=0.0001, verbose=0,
                                    warm_start=False))],
         verbose=False)
2023-08-07 21:26:24,101:INFO:save_model() successfully completed......................................
2023-08-07 21:26:24,452:INFO:Initializing save_model()
2023-08-07 21:26:24,453:INFO:save_model(model=LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=1000,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=123, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False), model_name=my_best_pipeline, prep_pipe_=Pipeline(memory=FastMemory(location=C:\Users\SAJJAD~1\AppData\Local\Temp\joblib),
         steps=[('numerical_imputer',
                 TransformerWrapper(exclude=None,
                                    include=['Number of times pregnant',
                                             'Plasma glucose concentration a 2 '
                                             'hours in an oral glucose '
                                             'tolerance test',
                                             'Diastolic blood pressure (mm Hg)',
                                             'Triceps skin fold thickness (mm)',
                                             '2-Hour serum insulin (mu U/ml)',
                                             'Body mass index (we...
                 TransformerWrapper(exclude=None, include=[],
                                    transformer=SimpleImputer(add_indicator=False,
                                                              copy=True,
                                                              fill_value=None,
                                                              keep_empty_features=False,
                                                              missing_values=nan,
                                                              strategy='most_frequent',
                                                              verbose='deprecated'))),
                ('clean_column_names',
                 TransformerWrapper(exclude=None, include=None,
                                    transformer=CleanColumnNames(match='[\\]\\[\\,\\{\\}\\"\\:]+')))],
         verbose=False), verbose=True, use_case=MLUsecase.CLASSIFICATION, kwargs={})
2023-08-07 21:26:24,453:INFO:Adding model into prep_pipe
2023-08-07 21:26:24,466:INFO:my_best_pipeline.pkl saved in current working directory
2023-08-07 21:26:24,484:INFO:Pipeline(memory=FastMemory(location=C:\Users\SAJJAD~1\AppData\Local\Temp\joblib),
         steps=[('numerical_imputer',
                 TransformerWrapper(exclude=None,
                                    include=['Number of times pregnant',
                                             'Plasma glucose concentration a 2 '
                                             'hours in an oral glucose '
                                             'tolerance test',
                                             'Diastolic blood pressure (mm Hg)',
                                             'Triceps skin fold thickness (mm)',
                                             '2-Hour serum insulin (mu U/ml)',
                                             'Body mass index (we...
                 TransformerWrapper(exclude=None, include=None,
                                    transformer=CleanColumnNames(match='[\\]\\[\\,\\{\\}\\"\\:]+'))),
                ('trained_model',
                 LogisticRegression(C=1.0, class_weight=None, dual=False,
                                    fit_intercept=True, intercept_scaling=1,
                                    l1_ratio=None, max_iter=1000,
                                    multi_class='auto', n_jobs=None,
                                    penalty='l2', random_state=123,
                                    solver='lbfgs', tol=0.0001, verbose=0,
                                    warm_start=False))],
         verbose=False)
2023-08-07 21:26:24,484:INFO:save_model() successfully completed......................................
2023-08-07 21:26:46,769:INFO:Initializing load_model()
2023-08-07 21:26:46,769:INFO:load_model(model_name=my_best_pipeline, platform=None, authentication=None, verbose=True)
2023-08-07 21:26:46,801:INFO:Initializing load_model()
2023-08-07 21:26:46,803:INFO:load_model(model_name=my_best_pipeline, platform=None, authentication=None, verbose=True)
